/**
 * Copyright (c) 2021 Wavious LLC.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// MODULE DFICH
// RANGE 0x03FF:0x0000
// WIDTH 32

#ifndef _DDR_DFICH_CSR_H_
#define _DDR_DFICH_CSR_H_

// Word Address 0x00000000 : DDR_DFICH_TOP_1_CFG (RW)
#define DDR_DFICH_TOP_1_CFG_TS_ENABLE__MSK                                                                   (  0x00000001 )
#define DDR_DFICH_TOP_1_CFG_TS_ENABLE__SHFT                                                                  (  0x00000000 )
#define DDR_DFICH_TOP_1_CFG_TS_RESET__MSK                                                                    (  0x00000002 )
#define DDR_DFICH_TOP_1_CFG_TS_RESET__SHFT                                                                   (  0x00000001 )
#define DDR_DFICH_TOP_1_CFG_WDATA_CLR__MSK                                                                   (  0x00000010 )
#define DDR_DFICH_TOP_1_CFG_WDATA_CLR__SHFT                                                                  (  0x00000004 )
#define DDR_DFICH_TOP_1_CFG_WDATA_HOLD__MSK                                                                  (  0x00000020 )
#define DDR_DFICH_TOP_1_CFG_WDATA_HOLD__SHFT                                                                 (  0x00000005 )
#define DDR_DFICH_TOP_1_CFG_WDATA_ENABLE__MSK                                                                (  0x00000040 )
#define DDR_DFICH_TOP_1_CFG_WDATA_ENABLE__SHFT                                                               (  0x00000006 )
#define DDR_DFICH_TOP_1_CFG_WDATA_UPDATE__MSK                                                                (  0x00000080 )
#define DDR_DFICH_TOP_1_CFG_WDATA_UPDATE__SHFT                                                               (  0x00000007 )
#define DDR_DFICH_TOP_1_CFG_RDATA_CLR__MSK                                                                   (  0x00000100 )
#define DDR_DFICH_TOP_1_CFG_RDATA_CLR__SHFT                                                                  (  0x00000008 )
#define DDR_DFICH_TOP_1_CFG_RDATA_ENABLE__MSK                                                                (  0x00000200 )
#define DDR_DFICH_TOP_1_CFG_RDATA_ENABLE__SHFT                                                               (  0x00000009 )
#define DDR_DFICH_TOP_1_CFG_RDATA_UPDATE__MSK                                                                (  0x00000400 )
#define DDR_DFICH_TOP_1_CFG_RDATA_UPDATE__SHFT                                                               (  0x0000000A )
#define DDR_DFICH_TOP_1_CFG_BUF_MODE__MSK                                                                    (  0x00001000 )
#define DDR_DFICH_TOP_1_CFG_BUF_MODE__SHFT                                                                   (  0x0000000C )
#define DDR_DFICH_TOP_1_CFG_BUF_CLK_EN__MSK                                                                  (  0x00002000 )
#define DDR_DFICH_TOP_1_CFG_BUF_CLK_EN__SHFT                                                                 (  0x0000000D )
#define DDR_DFICH_TOP_1_CFG_WCK_MODE__MSK                                                                    (  0x00010000 )
#define DDR_DFICH_TOP_1_CFG_WCK_MODE__SHFT                                                                   (  0x00000010 )
#define DDR_DFICH_TOP_1_CFG_CA_RDDATA_EN__MSK                                                                (  0x00020000 )
#define DDR_DFICH_TOP_1_CFG_CA_RDDATA_EN__SHFT                                                               (  0x00000011 )
#define DDR_DFICH_TOP_1_CFG_RDOUT_EN_OVR_SEL__MSK                                                            (  0x00040000 )
#define DDR_DFICH_TOP_1_CFG_RDOUT_EN_OVR_SEL__SHFT                                                           (  0x00000012 )
#define DDR_DFICH_TOP_1_CFG_RDOUT_EN_OVR__MSK                                                                (  0x00080000 )
#define DDR_DFICH_TOP_1_CFG_RDOUT_EN_OVR__SHFT                                                               (  0x00000013 )
#define DDR_DFICH_TOP_1_CFG_DQBYTE_RDVALID_MASK__MSK                                                         (  0xF0000000 )
#define DDR_DFICH_TOP_1_CFG_DQBYTE_RDVALID_MASK__SHFT                                                        (  0x0000001C )
#define DDR_DFICH_TOP_1_CFG__ADR                                                                             (  0x00000000 )
#define DDR_DFICH_TOP_1_CFG__WIDTH                                                                           (  32 )
#define DDR_DFICH_TOP_1_CFG__POR                                                                             (  0x00002000 )
#define DDR_DFICH_TOP_1_CFG__MSK                                                                             (  0xF00F37F3 )


// Word Address 0x00000004 : DDR_DFICH_TOP_2_CFG (RW)
#define DDR_DFICH_TOP_2_CFG_IG_LOOP_MODE__MSK                                                                (  0x00000001 )
#define DDR_DFICH_TOP_2_CFG_IG_LOOP_MODE__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_TOP_2_CFG_IG_LOAD_PTR__MSK                                                                 (  0x00000002 )
#define DDR_DFICH_TOP_2_CFG_IG_LOAD_PTR__SHFT                                                                (  0x00000001 )
#define DDR_DFICH_TOP_2_CFG_IG_NUM_LOOPS__MSK                                                                (  0x000000F0 )
#define DDR_DFICH_TOP_2_CFG_IG_NUM_LOOPS__SHFT                                                               (  0x00000004 )
#define DDR_DFICH_TOP_2_CFG_IG_STOP_PTR__MSK                                                                 (  0x00003F00 )
#define DDR_DFICH_TOP_2_CFG_IG_STOP_PTR__SHFT                                                                (  0x00000008 )
#define DDR_DFICH_TOP_2_CFG_IG_START_PTR__MSK                                                                (  0x003F0000 )
#define DDR_DFICH_TOP_2_CFG_IG_START_PTR__SHFT                                                               (  0x00000010 )
#define DDR_DFICH_TOP_2_CFG__ADR                                                                             (  0x00000004 )
#define DDR_DFICH_TOP_2_CFG__WIDTH                                                                           (  22 )
#define DDR_DFICH_TOP_2_CFG__POR                                                                             (  0x00000010 )
#define DDR_DFICH_TOP_2_CFG__MSK                                                                             (  0x003F3FF3 )


// Word Address 0x00000008 : DDR_DFICH_TOP_3_CFG (RW)
#define DDR_DFICH_TOP_3_CFG_TS_BRKPT_VAL__MSK                                                                (  0x0000FFFF )
#define DDR_DFICH_TOP_3_CFG_TS_BRKPT_VAL__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_TOP_3_CFG_TS_BRKPT_EN__MSK                                                                 (  0x00010000 )
#define DDR_DFICH_TOP_3_CFG_TS_BRKPT_EN__SHFT                                                                (  0x00000010 )
#define DDR_DFICH_TOP_3_CFG__ADR                                                                             (  0x00000008 )
#define DDR_DFICH_TOP_3_CFG__WIDTH                                                                           (  17 )
#define DDR_DFICH_TOP_3_CFG__POR                                                                             (  0x00000000 )
#define DDR_DFICH_TOP_3_CFG__MSK                                                                             (  0x0001FFFF )


// Word Address 0x0000000c : DDR_DFICH_TOP_STA (R)
#define DDR_DFICH_TOP_STA_IG_STATE__MSK                                                                      (  0x00000003 )
#define DDR_DFICH_TOP_STA_IG_STATE__SHFT                                                                     (  0x00000000 )
#define DDR_DFICH_TOP_STA_IG_STATE_UPD__MSK                                                                  (  0x00000004 )
#define DDR_DFICH_TOP_STA_IG_STATE_UPD__SHFT                                                                 (  0x00000002 )
#define DDR_DFICH_TOP_STA_EG_STATE__MSK                                                                      (  0x00000030 )
#define DDR_DFICH_TOP_STA_EG_STATE__SHFT                                                                     (  0x00000004 )
#define DDR_DFICH_TOP_STA_EG_STATE_UPD__MSK                                                                  (  0x00000040 )
#define DDR_DFICH_TOP_STA_EG_STATE_UPD__SHFT                                                                 (  0x00000006 )
#define DDR_DFICH_TOP_STA__ADR                                                                               (  0x0000000c )
#define DDR_DFICH_TOP_STA__WIDTH                                                                             (   7 )
#define DDR_DFICH_TOP_STA__POR                                                                               (  0x00000000 )
#define DDR_DFICH_TOP_STA__MSK                                                                               (  0x00000077 )


// Word Address 0x00000010 : DDR_DFICH_IG_DATA_CFG (RW)
#define DDR_DFICH_IG_DATA_CFG_WDATA__MSK                                                                     (  0xFFFFFFFF )
#define DDR_DFICH_IG_DATA_CFG_WDATA__SHFT                                                                    (  0x00000000 )
#define DDR_DFICH_IG_DATA_CFG__ADR                                                                           (  0x00000010 )
#define DDR_DFICH_IG_DATA_CFG__WIDTH                                                                         (  32 )
#define DDR_DFICH_IG_DATA_CFG__POR                                                                           (  0x00000000 )
#define DDR_DFICH_IG_DATA_CFG__MSK                                                                           (  0xFFFFFFFF )


// Word Address 0x00000014 : DDR_DFICH_EG_DATA_STA (R)
#define DDR_DFICH_EG_DATA_STA_RDATA__MSK                                                                     (  0xFFFFFFFF )
#define DDR_DFICH_EG_DATA_STA_RDATA__SHFT                                                                    (  0x00000000 )
#define DDR_DFICH_EG_DATA_STA__ADR                                                                           (  0x00000014 )
#define DDR_DFICH_EG_DATA_STA__WIDTH                                                                         (  32 )
#define DDR_DFICH_EG_DATA_STA__POR                                                                           (  0x00000000 )
#define DDR_DFICH_EG_DATA_STA__MSK                                                                           (  0xFFFFFFFF )


// Word Address 0x00000018 : DDR_DFICH_WRC_M0_CFG (RW)
#define DDR_DFICH_WRC_M0_CFG_PIPE_EN__MSK                                                                    (  0x00000001 )
#define DDR_DFICH_WRC_M0_CFG_PIPE_EN__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_WRC_M0_CFG_POST_GB_FC_DLY__MSK                                                             (  0x00000030 )
#define DDR_DFICH_WRC_M0_CFG_POST_GB_FC_DLY__SHFT                                                            (  0x00000004 )
#define DDR_DFICH_WRC_M0_CFG_GB_MODE__MSK                                                                    (  0x0000F000 )
#define DDR_DFICH_WRC_M0_CFG_GB_MODE__SHFT                                                                   (  0x0000000C )
#define DDR_DFICH_WRC_M0_CFG__ADR                                                                            (  0x00000018 )
#define DDR_DFICH_WRC_M0_CFG__WIDTH                                                                          (  16 )
#define DDR_DFICH_WRC_M0_CFG__POR                                                                            (  0x00005000 )
#define DDR_DFICH_WRC_M0_CFG__MSK                                                                            (  0x0000F031 )


// Word Address 0x0000001c : DDR_DFICH_WRC_M1_CFG (RW)
#define DDR_DFICH_WRC_M1_CFG_PIPE_EN__MSK                                                                    (  0x00000001 )
#define DDR_DFICH_WRC_M1_CFG_PIPE_EN__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_WRC_M1_CFG_POST_GB_FC_DLY__MSK                                                             (  0x00000030 )
#define DDR_DFICH_WRC_M1_CFG_POST_GB_FC_DLY__SHFT                                                            (  0x00000004 )
#define DDR_DFICH_WRC_M1_CFG_GB_MODE__MSK                                                                    (  0x0000F000 )
#define DDR_DFICH_WRC_M1_CFG_GB_MODE__SHFT                                                                   (  0x0000000C )
#define DDR_DFICH_WRC_M1_CFG__ADR                                                                            (  0x0000001c )
#define DDR_DFICH_WRC_M1_CFG__WIDTH                                                                          (  16 )
#define DDR_DFICH_WRC_M1_CFG__POR                                                                            (  0x00005000 )
#define DDR_DFICH_WRC_M1_CFG__MSK                                                                            (  0x0000F031 )


// Word Address 0x00000020 : DDR_DFICH_WRCCTRL_M0_CFG (RW)
#define DDR_DFICH_WRCCTRL_M0_CFG_PIPE_EN__MSK                                                                (  0x00000001 )
#define DDR_DFICH_WRCCTRL_M0_CFG_PIPE_EN__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_WRCCTRL_M0_CFG_POST_GB_FC_DLY__MSK                                                         (  0x00000030 )
#define DDR_DFICH_WRCCTRL_M0_CFG_POST_GB_FC_DLY__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_WRCCTRL_M0_CFG_GB_MODE__MSK                                                                (  0x0000F000 )
#define DDR_DFICH_WRCCTRL_M0_CFG_GB_MODE__SHFT                                                               (  0x0000000C )
#define DDR_DFICH_WRCCTRL_M0_CFG__ADR                                                                        (  0x00000020 )
#define DDR_DFICH_WRCCTRL_M0_CFG__WIDTH                                                                      (  16 )
#define DDR_DFICH_WRCCTRL_M0_CFG__POR                                                                        (  0x00005000 )
#define DDR_DFICH_WRCCTRL_M0_CFG__MSK                                                                        (  0x0000F031 )


// Word Address 0x00000024 : DDR_DFICH_WRCCTRL_M1_CFG (RW)
#define DDR_DFICH_WRCCTRL_M1_CFG_PIPE_EN__MSK                                                                (  0x00000001 )
#define DDR_DFICH_WRCCTRL_M1_CFG_PIPE_EN__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_WRCCTRL_M1_CFG_POST_GB_FC_DLY__MSK                                                         (  0x00000030 )
#define DDR_DFICH_WRCCTRL_M1_CFG_POST_GB_FC_DLY__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_WRCCTRL_M1_CFG_GB_MODE__MSK                                                                (  0x0000F000 )
#define DDR_DFICH_WRCCTRL_M1_CFG_GB_MODE__SHFT                                                               (  0x0000000C )
#define DDR_DFICH_WRCCTRL_M1_CFG__ADR                                                                        (  0x00000024 )
#define DDR_DFICH_WRCCTRL_M1_CFG__WIDTH                                                                      (  16 )
#define DDR_DFICH_WRCCTRL_M1_CFG__POR                                                                        (  0x00005000 )
#define DDR_DFICH_WRCCTRL_M1_CFG__MSK                                                                        (  0x0000F031 )


// Word Address 0x00000028 : DDR_DFICH_CKCTRL_M0_CFG (RW)
#define DDR_DFICH_CKCTRL_M0_CFG_PIPE_EN__MSK                                                                 (  0x00000001 )
#define DDR_DFICH_CKCTRL_M0_CFG_PIPE_EN__SHFT                                                                (  0x00000000 )
#define DDR_DFICH_CKCTRL_M0_CFG_POST_GB_FC_DLY__MSK                                                          (  0x00000030 )
#define DDR_DFICH_CKCTRL_M0_CFG_POST_GB_FC_DLY__SHFT                                                         (  0x00000004 )
#define DDR_DFICH_CKCTRL_M0_CFG_GB_MODE__MSK                                                                 (  0x0000F000 )
#define DDR_DFICH_CKCTRL_M0_CFG_GB_MODE__SHFT                                                                (  0x0000000C )
#define DDR_DFICH_CKCTRL_M0_CFG__ADR                                                                         (  0x00000028 )
#define DDR_DFICH_CKCTRL_M0_CFG__WIDTH                                                                       (  16 )
#define DDR_DFICH_CKCTRL_M0_CFG__POR                                                                         (  0x00005000 )
#define DDR_DFICH_CKCTRL_M0_CFG__MSK                                                                         (  0x0000F031 )


// Word Address 0x0000002c : DDR_DFICH_CKCTRL_M1_CFG (RW)
#define DDR_DFICH_CKCTRL_M1_CFG_PIPE_EN__MSK                                                                 (  0x00000001 )
#define DDR_DFICH_CKCTRL_M1_CFG_PIPE_EN__SHFT                                                                (  0x00000000 )
#define DDR_DFICH_CKCTRL_M1_CFG_POST_GB_FC_DLY__MSK                                                          (  0x00000030 )
#define DDR_DFICH_CKCTRL_M1_CFG_POST_GB_FC_DLY__SHFT                                                         (  0x00000004 )
#define DDR_DFICH_CKCTRL_M1_CFG_GB_MODE__MSK                                                                 (  0x0000F000 )
#define DDR_DFICH_CKCTRL_M1_CFG_GB_MODE__SHFT                                                                (  0x0000000C )
#define DDR_DFICH_CKCTRL_M1_CFG__ADR                                                                         (  0x0000002c )
#define DDR_DFICH_CKCTRL_M1_CFG__WIDTH                                                                       (  16 )
#define DDR_DFICH_CKCTRL_M1_CFG__POR                                                                         (  0x00005000 )
#define DDR_DFICH_CKCTRL_M1_CFG__MSK                                                                         (  0x0000F031 )


// Word Address 0x00000030 : DDR_DFICH_RDC_M0_CFG (RW)
#define DDR_DFICH_RDC_M0_CFG_GB_MODE__MSK                                                                    (  0x0000000F )
#define DDR_DFICH_RDC_M0_CFG_GB_MODE__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_RDC_M0_CFG__ADR                                                                            (  0x00000030 )
#define DDR_DFICH_RDC_M0_CFG__WIDTH                                                                          (   4 )
#define DDR_DFICH_RDC_M0_CFG__POR                                                                            (  0x00000006 )
#define DDR_DFICH_RDC_M0_CFG__MSK                                                                            (  0x0000000F )


// Word Address 0x00000034 : DDR_DFICH_RDC_M1_CFG (RW)
#define DDR_DFICH_RDC_M1_CFG_GB_MODE__MSK                                                                    (  0x0000000F )
#define DDR_DFICH_RDC_M1_CFG_GB_MODE__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_RDC_M1_CFG__ADR                                                                            (  0x00000034 )
#define DDR_DFICH_RDC_M1_CFG__WIDTH                                                                          (   4 )
#define DDR_DFICH_RDC_M1_CFG__POR                                                                            (  0x00000006 )
#define DDR_DFICH_RDC_M1_CFG__MSK                                                                            (  0x0000000F )


// Word Address 0x00000038 : DDR_DFICH_RCTRL_M0_CFG (RW)
#define DDR_DFICH_RCTRL_M0_CFG_PIPE_EN__MSK                                                                  (  0x00000001 )
#define DDR_DFICH_RCTRL_M0_CFG_PIPE_EN__SHFT                                                                 (  0x00000000 )
#define DDR_DFICH_RCTRL_M0_CFG_POST_GB_FC_DLY__MSK                                                           (  0x00000070 )
#define DDR_DFICH_RCTRL_M0_CFG_POST_GB_FC_DLY__SHFT                                                          (  0x00000004 )
#define DDR_DFICH_RCTRL_M0_CFG_GB_MODE__MSK                                                                  (  0x0000F000 )
#define DDR_DFICH_RCTRL_M0_CFG_GB_MODE__SHFT                                                                 (  0x0000000C )
#define DDR_DFICH_RCTRL_M0_CFG__ADR                                                                          (  0x00000038 )
#define DDR_DFICH_RCTRL_M0_CFG__WIDTH                                                                        (  16 )
#define DDR_DFICH_RCTRL_M0_CFG__POR                                                                          (  0x00005000 )
#define DDR_DFICH_RCTRL_M0_CFG__MSK                                                                          (  0x0000F071 )


// Word Address 0x0000003c : DDR_DFICH_RCTRL_M1_CFG (RW)
#define DDR_DFICH_RCTRL_M1_CFG_PIPE_EN__MSK                                                                  (  0x00000001 )
#define DDR_DFICH_RCTRL_M1_CFG_PIPE_EN__SHFT                                                                 (  0x00000000 )
#define DDR_DFICH_RCTRL_M1_CFG_POST_GB_FC_DLY__MSK                                                           (  0x00000070 )
#define DDR_DFICH_RCTRL_M1_CFG_POST_GB_FC_DLY__SHFT                                                          (  0x00000004 )
#define DDR_DFICH_RCTRL_M1_CFG_GB_MODE__MSK                                                                  (  0x0000F000 )
#define DDR_DFICH_RCTRL_M1_CFG_GB_MODE__SHFT                                                                 (  0x0000000C )
#define DDR_DFICH_RCTRL_M1_CFG__ADR                                                                          (  0x0000003c )
#define DDR_DFICH_RCTRL_M1_CFG__WIDTH                                                                        (  16 )
#define DDR_DFICH_RCTRL_M1_CFG__POR                                                                          (  0x00005000 )
#define DDR_DFICH_RCTRL_M1_CFG__MSK                                                                          (  0x0000F071 )


// Word Address 0x00000040 : DDR_DFICH_WCTRL_M0_CFG (RW)
#define DDR_DFICH_WCTRL_M0_CFG_PIPE_EN__MSK                                                                  (  0x00000001 )
#define DDR_DFICH_WCTRL_M0_CFG_PIPE_EN__SHFT                                                                 (  0x00000000 )
#define DDR_DFICH_WCTRL_M0_CFG_POST_GB_FC_DLY__MSK                                                           (  0x00000070 )
#define DDR_DFICH_WCTRL_M0_CFG_POST_GB_FC_DLY__SHFT                                                          (  0x00000004 )
#define DDR_DFICH_WCTRL_M0_CFG_GB_MODE__MSK                                                                  (  0x0000F000 )
#define DDR_DFICH_WCTRL_M0_CFG_GB_MODE__SHFT                                                                 (  0x0000000C )
#define DDR_DFICH_WCTRL_M0_CFG__ADR                                                                          (  0x00000040 )
#define DDR_DFICH_WCTRL_M0_CFG__WIDTH                                                                        (  16 )
#define DDR_DFICH_WCTRL_M0_CFG__POR                                                                          (  0x00005000 )
#define DDR_DFICH_WCTRL_M0_CFG__MSK                                                                          (  0x0000F071 )


// Word Address 0x00000044 : DDR_DFICH_WCTRL_M1_CFG (RW)
#define DDR_DFICH_WCTRL_M1_CFG_PIPE_EN__MSK                                                                  (  0x00000001 )
#define DDR_DFICH_WCTRL_M1_CFG_PIPE_EN__SHFT                                                                 (  0x00000000 )
#define DDR_DFICH_WCTRL_M1_CFG_POST_GB_FC_DLY__MSK                                                           (  0x00000070 )
#define DDR_DFICH_WCTRL_M1_CFG_POST_GB_FC_DLY__SHFT                                                          (  0x00000004 )
#define DDR_DFICH_WCTRL_M1_CFG_GB_MODE__MSK                                                                  (  0x0000F000 )
#define DDR_DFICH_WCTRL_M1_CFG_GB_MODE__SHFT                                                                 (  0x0000000C )
#define DDR_DFICH_WCTRL_M1_CFG__ADR                                                                          (  0x00000044 )
#define DDR_DFICH_WCTRL_M1_CFG__WIDTH                                                                        (  16 )
#define DDR_DFICH_WCTRL_M1_CFG__POR                                                                          (  0x00005000 )
#define DDR_DFICH_WCTRL_M1_CFG__MSK                                                                          (  0x0000F071 )


// Word Address 0x00000048 : DDR_DFICH_WENCTRL_M0_CFG (RW)
#define DDR_DFICH_WENCTRL_M0_CFG_PIPE_EN__MSK                                                                (  0x00000001 )
#define DDR_DFICH_WENCTRL_M0_CFG_PIPE_EN__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_WENCTRL_M0_CFG_POST_GB_FC_DLY__MSK                                                         (  0x000000F0 )
#define DDR_DFICH_WENCTRL_M0_CFG_POST_GB_FC_DLY__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_WENCTRL_M0_CFG_GB_MODE__MSK                                                                (  0x0000F000 )
#define DDR_DFICH_WENCTRL_M0_CFG_GB_MODE__SHFT                                                               (  0x0000000C )
#define DDR_DFICH_WENCTRL_M0_CFG__ADR                                                                        (  0x00000048 )
#define DDR_DFICH_WENCTRL_M0_CFG__WIDTH                                                                      (  16 )
#define DDR_DFICH_WENCTRL_M0_CFG__POR                                                                        (  0x00005000 )
#define DDR_DFICH_WENCTRL_M0_CFG__MSK                                                                        (  0x0000F0F1 )


// Word Address 0x0000004c : DDR_DFICH_WENCTRL_M1_CFG (RW)
#define DDR_DFICH_WENCTRL_M1_CFG_PIPE_EN__MSK                                                                (  0x00000001 )
#define DDR_DFICH_WENCTRL_M1_CFG_PIPE_EN__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_WENCTRL_M1_CFG_POST_GB_FC_DLY__MSK                                                         (  0x000000F0 )
#define DDR_DFICH_WENCTRL_M1_CFG_POST_GB_FC_DLY__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_WENCTRL_M1_CFG_GB_MODE__MSK                                                                (  0x0000F000 )
#define DDR_DFICH_WENCTRL_M1_CFG_GB_MODE__SHFT                                                               (  0x0000000C )
#define DDR_DFICH_WENCTRL_M1_CFG__ADR                                                                        (  0x0000004c )
#define DDR_DFICH_WENCTRL_M1_CFG__WIDTH                                                                      (  16 )
#define DDR_DFICH_WENCTRL_M1_CFG__POR                                                                        (  0x00005000 )
#define DDR_DFICH_WENCTRL_M1_CFG__MSK                                                                        (  0x0000F0F1 )


// Word Address 0x00000050 : DDR_DFICH_WCKCTRL_M0_CFG (RW)
#define DDR_DFICH_WCKCTRL_M0_CFG_PIPE_EN__MSK                                                                (  0x00000001 )
#define DDR_DFICH_WCKCTRL_M0_CFG_PIPE_EN__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_WCKCTRL_M0_CFG_POST_GB_FC_DLY__MSK                                                         (  0x00000070 )
#define DDR_DFICH_WCKCTRL_M0_CFG_POST_GB_FC_DLY__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_WCKCTRL_M0_CFG_GB_MODE__MSK                                                                (  0x0000F000 )
#define DDR_DFICH_WCKCTRL_M0_CFG_GB_MODE__SHFT                                                               (  0x0000000C )
#define DDR_DFICH_WCKCTRL_M0_CFG__ADR                                                                        (  0x00000050 )
#define DDR_DFICH_WCKCTRL_M0_CFG__WIDTH                                                                      (  16 )
#define DDR_DFICH_WCKCTRL_M0_CFG__POR                                                                        (  0x00005000 )
#define DDR_DFICH_WCKCTRL_M0_CFG__MSK                                                                        (  0x0000F071 )


// Word Address 0x00000054 : DDR_DFICH_WCKCTRL_M1_CFG (RW)
#define DDR_DFICH_WCKCTRL_M1_CFG_PIPE_EN__MSK                                                                (  0x00000001 )
#define DDR_DFICH_WCKCTRL_M1_CFG_PIPE_EN__SHFT                                                               (  0x00000000 )
#define DDR_DFICH_WCKCTRL_M1_CFG_POST_GB_FC_DLY__MSK                                                         (  0x00000070 )
#define DDR_DFICH_WCKCTRL_M1_CFG_POST_GB_FC_DLY__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_WCKCTRL_M1_CFG_GB_MODE__MSK                                                                (  0x0000F000 )
#define DDR_DFICH_WCKCTRL_M1_CFG_GB_MODE__SHFT                                                               (  0x0000000C )
#define DDR_DFICH_WCKCTRL_M1_CFG__ADR                                                                        (  0x00000054 )
#define DDR_DFICH_WCKCTRL_M1_CFG__WIDTH                                                                      (  16 )
#define DDR_DFICH_WCKCTRL_M1_CFG__POR                                                                        (  0x00005000 )
#define DDR_DFICH_WCKCTRL_M1_CFG__MSK                                                                        (  0x0000F071 )


// Word Address 0x00000058 : DDR_DFICH_WRD_M0_CFG (RW)
#define DDR_DFICH_WRD_M0_CFG_PIPE_EN__MSK                                                                    (  0x00000001 )
#define DDR_DFICH_WRD_M0_CFG_PIPE_EN__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_WRD_M0_CFG_POST_GB_FC_DLY__MSK                                                             (  0x00000030 )
#define DDR_DFICH_WRD_M0_CFG_POST_GB_FC_DLY__SHFT                                                            (  0x00000004 )
#define DDR_DFICH_WRD_M0_CFG_GB_MODE__MSK                                                                    (  0x0000F000 )
#define DDR_DFICH_WRD_M0_CFG_GB_MODE__SHFT                                                                   (  0x0000000C )
#define DDR_DFICH_WRD_M0_CFG__ADR                                                                            (  0x00000058 )
#define DDR_DFICH_WRD_M0_CFG__WIDTH                                                                          (  16 )
#define DDR_DFICH_WRD_M0_CFG__POR                                                                            (  0x00005000 )
#define DDR_DFICH_WRD_M0_CFG__MSK                                                                            (  0x0000F031 )


// Word Address 0x0000005c : DDR_DFICH_WRD_M1_CFG (RW)
#define DDR_DFICH_WRD_M1_CFG_PIPE_EN__MSK                                                                    (  0x00000001 )
#define DDR_DFICH_WRD_M1_CFG_PIPE_EN__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_WRD_M1_CFG_POST_GB_FC_DLY__MSK                                                             (  0x00000030 )
#define DDR_DFICH_WRD_M1_CFG_POST_GB_FC_DLY__SHFT                                                            (  0x00000004 )
#define DDR_DFICH_WRD_M1_CFG_GB_MODE__MSK                                                                    (  0x0000F000 )
#define DDR_DFICH_WRD_M1_CFG_GB_MODE__SHFT                                                                   (  0x0000000C )
#define DDR_DFICH_WRD_M1_CFG__ADR                                                                            (  0x0000005c )
#define DDR_DFICH_WRD_M1_CFG__WIDTH                                                                          (  16 )
#define DDR_DFICH_WRD_M1_CFG__POR                                                                            (  0x00005000 )
#define DDR_DFICH_WRD_M1_CFG__MSK                                                                            (  0x0000F031 )


// Word Address 0x00000060 : DDR_DFICH_RDD_M0_CFG (RW)
#define DDR_DFICH_RDD_M0_CFG_GB_MODE__MSK                                                                    (  0x0000000F )
#define DDR_DFICH_RDD_M0_CFG_GB_MODE__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_RDD_M0_CFG__ADR                                                                            (  0x00000060 )
#define DDR_DFICH_RDD_M0_CFG__WIDTH                                                                          (   4 )
#define DDR_DFICH_RDD_M0_CFG__POR                                                                            (  0x00000006 )
#define DDR_DFICH_RDD_M0_CFG__MSK                                                                            (  0x0000000F )


// Word Address 0x00000064 : DDR_DFICH_RDD_M1_CFG (RW)
#define DDR_DFICH_RDD_M1_CFG_GB_MODE__MSK                                                                    (  0x0000000F )
#define DDR_DFICH_RDD_M1_CFG_GB_MODE__SHFT                                                                   (  0x00000000 )
#define DDR_DFICH_RDD_M1_CFG__ADR                                                                            (  0x00000064 )
#define DDR_DFICH_RDD_M1_CFG__WIDTH                                                                          (   4 )
#define DDR_DFICH_RDD_M1_CFG__POR                                                                            (  0x00000006 )
#define DDR_DFICH_RDD_M1_CFG__MSK                                                                            (  0x0000000F )


// Word Address 0x00000068 : DDR_DFICH_CTRL0_M0_CFG (RW)
#define DDR_DFICH_CTRL0_M0_CFG_WR_INTF_PIPE_EN__MSK                                                          (  0x00000001 )
#define DDR_DFICH_CTRL0_M0_CFG_WR_INTF_PIPE_EN__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CTRL0_M0_CFG_RD_INTF_PIPE_EN__MSK                                                          (  0x00000002 )
#define DDR_DFICH_CTRL0_M0_CFG_RD_INTF_PIPE_EN__SHFT                                                         (  0x00000001 )
#define DDR_DFICH_CTRL0_M0_CFG__ADR                                                                          (  0x00000068 )
#define DDR_DFICH_CTRL0_M0_CFG__WIDTH                                                                        (   2 )
#define DDR_DFICH_CTRL0_M0_CFG__POR                                                                          (  0x00000003 )
#define DDR_DFICH_CTRL0_M0_CFG__MSK                                                                          (  0x00000003 )


// Word Address 0x0000006c : DDR_DFICH_CTRL0_M1_CFG (RW)
#define DDR_DFICH_CTRL0_M1_CFG_WR_INTF_PIPE_EN__MSK                                                          (  0x00000001 )
#define DDR_DFICH_CTRL0_M1_CFG_WR_INTF_PIPE_EN__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CTRL0_M1_CFG_RD_INTF_PIPE_EN__MSK                                                          (  0x00000002 )
#define DDR_DFICH_CTRL0_M1_CFG_RD_INTF_PIPE_EN__SHFT                                                         (  0x00000001 )
#define DDR_DFICH_CTRL0_M1_CFG__ADR                                                                          (  0x0000006c )
#define DDR_DFICH_CTRL0_M1_CFG__WIDTH                                                                        (   2 )
#define DDR_DFICH_CTRL0_M1_CFG__POR                                                                          (  0x00000003 )
#define DDR_DFICH_CTRL0_M1_CFG__MSK                                                                          (  0x00000003 )


// Word Address 0x00000070 : DDR_DFICH_CTRL1_M0_CFG (RW)
#define DDR_DFICH_CTRL1_M0_CFG_DQ_WRTRAFFIC_OVR_SEL__MSK                                                     (  0x00000001 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_WRTRAFFIC_OVR_SEL__SHFT                                                    (  0x00000000 )
#define DDR_DFICH_CTRL1_M0_CFG_DQS_WRTRAFFIC_OVR_SEL__MSK                                                    (  0x00000002 )
#define DDR_DFICH_CTRL1_M0_CFG_DQS_WRTRAFFIC_OVR_SEL__SHFT                                                   (  0x00000001 )
#define DDR_DFICH_CTRL1_M0_CFG_CA_TRAFFIC_OVR_SEL__MSK                                                       (  0x00000004 )
#define DDR_DFICH_CTRL1_M0_CFG_CA_TRAFFIC_OVR_SEL__SHFT                                                      (  0x00000002 )
#define DDR_DFICH_CTRL1_M0_CFG_CK_TRAFFIC_OVR_SEL__MSK                                                       (  0x00000008 )
#define DDR_DFICH_CTRL1_M0_CFG_CK_TRAFFIC_OVR_SEL__SHFT                                                      (  0x00000003 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_WRTRAFFIC_OVR__MSK                                                         (  0x00000010 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_WRTRAFFIC_OVR__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_CTRL1_M0_CFG_DQS_WRTRAFFIC_OVR__MSK                                                        (  0x00000020 )
#define DDR_DFICH_CTRL1_M0_CFG_DQS_WRTRAFFIC_OVR__SHFT                                                       (  0x00000005 )
#define DDR_DFICH_CTRL1_M0_CFG_CA_TRAFFIC_OVR__MSK                                                           (  0x00000040 )
#define DDR_DFICH_CTRL1_M0_CFG_CA_TRAFFIC_OVR__SHFT                                                          (  0x00000006 )
#define DDR_DFICH_CTRL1_M0_CFG_CK_TRAFFIC_OVR__MSK                                                           (  0x00000080 )
#define DDR_DFICH_CTRL1_M0_CFG_CK_TRAFFIC_OVR__SHFT                                                          (  0x00000007 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_RDTRAFFIC_OVR_SEL__MSK                                                     (  0x00000100 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_RDTRAFFIC_OVR_SEL__SHFT                                                    (  0x00000008 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_RDTRAFFIC_OVR__MSK                                                         (  0x00000200 )
#define DDR_DFICH_CTRL1_M0_CFG_DQ_RDTRAFFIC_OVR__SHFT                                                        (  0x00000009 )
#define DDR_DFICH_CTRL1_M0_CFG__ADR                                                                          (  0x00000070 )
#define DDR_DFICH_CTRL1_M0_CFG__WIDTH                                                                        (  10 )
#define DDR_DFICH_CTRL1_M0_CFG__POR                                                                          (  0x000000FF )
#define DDR_DFICH_CTRL1_M0_CFG__MSK                                                                          (  0x000003FF )


// Word Address 0x00000074 : DDR_DFICH_CTRL1_M1_CFG (RW)
#define DDR_DFICH_CTRL1_M1_CFG_DQ_WRTRAFFIC_OVR_SEL__MSK                                                     (  0x00000001 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_WRTRAFFIC_OVR_SEL__SHFT                                                    (  0x00000000 )
#define DDR_DFICH_CTRL1_M1_CFG_DQS_WRTRAFFIC_OVR_SEL__MSK                                                    (  0x00000002 )
#define DDR_DFICH_CTRL1_M1_CFG_DQS_WRTRAFFIC_OVR_SEL__SHFT                                                   (  0x00000001 )
#define DDR_DFICH_CTRL1_M1_CFG_CA_TRAFFIC_OVR_SEL__MSK                                                       (  0x00000004 )
#define DDR_DFICH_CTRL1_M1_CFG_CA_TRAFFIC_OVR_SEL__SHFT                                                      (  0x00000002 )
#define DDR_DFICH_CTRL1_M1_CFG_CK_TRAFFIC_OVR_SEL__MSK                                                       (  0x00000008 )
#define DDR_DFICH_CTRL1_M1_CFG_CK_TRAFFIC_OVR_SEL__SHFT                                                      (  0x00000003 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_WRTRAFFIC_OVR__MSK                                                         (  0x00000010 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_WRTRAFFIC_OVR__SHFT                                                        (  0x00000004 )
#define DDR_DFICH_CTRL1_M1_CFG_DQS_WRTRAFFIC_OVR__MSK                                                        (  0x00000020 )
#define DDR_DFICH_CTRL1_M1_CFG_DQS_WRTRAFFIC_OVR__SHFT                                                       (  0x00000005 )
#define DDR_DFICH_CTRL1_M1_CFG_CA_TRAFFIC_OVR__MSK                                                           (  0x00000040 )
#define DDR_DFICH_CTRL1_M1_CFG_CA_TRAFFIC_OVR__SHFT                                                          (  0x00000006 )
#define DDR_DFICH_CTRL1_M1_CFG_CK_TRAFFIC_OVR__MSK                                                           (  0x00000080 )
#define DDR_DFICH_CTRL1_M1_CFG_CK_TRAFFIC_OVR__SHFT                                                          (  0x00000007 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_RDTRAFFIC_OVR_SEL__MSK                                                     (  0x00000100 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_RDTRAFFIC_OVR_SEL__SHFT                                                    (  0x00000008 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_RDTRAFFIC_OVR__MSK                                                         (  0x00000200 )
#define DDR_DFICH_CTRL1_M1_CFG_DQ_RDTRAFFIC_OVR__SHFT                                                        (  0x00000009 )
#define DDR_DFICH_CTRL1_M1_CFG__ADR                                                                          (  0x00000074 )
#define DDR_DFICH_CTRL1_M1_CFG__WIDTH                                                                        (  10 )
#define DDR_DFICH_CTRL1_M1_CFG__POR                                                                          (  0x000000FF )
#define DDR_DFICH_CTRL1_M1_CFG__MSK                                                                          (  0x000003FF )


// Word Address 0x00000078 : DDR_DFICH_CTRL2_M0_CFG (RW)
#define DDR_DFICH_CTRL2_M0_CFG_DQ_WRCLK_EN_PULSE_EXT__MSK                                                    (  0x0000000F )
#define DDR_DFICH_CTRL2_M0_CFG_DQ_WRCLK_EN_PULSE_EXT__SHFT                                                   (  0x00000000 )
#define DDR_DFICH_CTRL2_M0_CFG_DQS_WRCLK_EN_PULSE_EXT__MSK                                                   (  0x000000F0 )
#define DDR_DFICH_CTRL2_M0_CFG_DQS_WRCLK_EN_PULSE_EXT__SHFT                                                  (  0x00000004 )
#define DDR_DFICH_CTRL2_M0_CFG_CA_CLK_EN_PULSE_EXT__MSK                                                      (  0x00000F00 )
#define DDR_DFICH_CTRL2_M0_CFG_CA_CLK_EN_PULSE_EXT__SHFT                                                     (  0x00000008 )
#define DDR_DFICH_CTRL2_M0_CFG_CK_CLK_EN_PULSE_EXT__MSK                                                      (  0x0000F000 )
#define DDR_DFICH_CTRL2_M0_CFG_CK_CLK_EN_PULSE_EXT__SHFT                                                     (  0x0000000C )
#define DDR_DFICH_CTRL2_M0_CFG_RDCLK_EN_PULSE_EXT__MSK                                                       (  0x000F0000 )
#define DDR_DFICH_CTRL2_M0_CFG_RDCLK_EN_PULSE_EXT__SHFT                                                      (  0x00000010 )
#define DDR_DFICH_CTRL2_M0_CFG__ADR                                                                          (  0x00000078 )
#define DDR_DFICH_CTRL2_M0_CFG__WIDTH                                                                        (  20 )
#define DDR_DFICH_CTRL2_M0_CFG__POR                                                                          (  0x000F0033 )
#define DDR_DFICH_CTRL2_M0_CFG__MSK                                                                          (  0x000FFFFF )


// Word Address 0x0000007c : DDR_DFICH_CTRL2_M1_CFG (RW)
#define DDR_DFICH_CTRL2_M1_CFG_DQ_WRCLK_EN_PULSE_EXT__MSK                                                    (  0x0000000F )
#define DDR_DFICH_CTRL2_M1_CFG_DQ_WRCLK_EN_PULSE_EXT__SHFT                                                   (  0x00000000 )
#define DDR_DFICH_CTRL2_M1_CFG_DQS_WRCLK_EN_PULSE_EXT__MSK                                                   (  0x000000F0 )
#define DDR_DFICH_CTRL2_M1_CFG_DQS_WRCLK_EN_PULSE_EXT__SHFT                                                  (  0x00000004 )
#define DDR_DFICH_CTRL2_M1_CFG_CA_CLK_EN_PULSE_EXT__MSK                                                      (  0x00000F00 )
#define DDR_DFICH_CTRL2_M1_CFG_CA_CLK_EN_PULSE_EXT__SHFT                                                     (  0x00000008 )
#define DDR_DFICH_CTRL2_M1_CFG_CK_CLK_EN_PULSE_EXT__MSK                                                      (  0x0000F000 )
#define DDR_DFICH_CTRL2_M1_CFG_CK_CLK_EN_PULSE_EXT__SHFT                                                     (  0x0000000C )
#define DDR_DFICH_CTRL2_M1_CFG_RDCLK_EN_PULSE_EXT__MSK                                                       (  0x000F0000 )
#define DDR_DFICH_CTRL2_M1_CFG_RDCLK_EN_PULSE_EXT__SHFT                                                      (  0x00000010 )
#define DDR_DFICH_CTRL2_M1_CFG__ADR                                                                          (  0x0000007c )
#define DDR_DFICH_CTRL2_M1_CFG__WIDTH                                                                        (  20 )
#define DDR_DFICH_CTRL2_M1_CFG__POR                                                                          (  0x000F0033 )
#define DDR_DFICH_CTRL2_M1_CFG__MSK                                                                          (  0x000FFFFF )


// Word Address 0x00000080 : DDR_DFICH_CTRL3_M0_CFG (RW)
#define DDR_DFICH_CTRL3_M0_CFG_WRD_CS_PHASE_EXT__MSK                                                         (  0x0000003F )
#define DDR_DFICH_CTRL3_M0_CFG_WRD_CS_PHASE_EXT__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_CTRL3_M0_CFG_WRD_EN_PHASE_EXT__MSK                                                         (  0x00003F00 )
#define DDR_DFICH_CTRL3_M0_CFG_WRD_EN_PHASE_EXT__SHFT                                                        (  0x00000008 )
#define DDR_DFICH_CTRL3_M0_CFG_WRD_OE_PHASE_EXT__MSK                                                         (  0x003F0000 )
#define DDR_DFICH_CTRL3_M0_CFG_WRD_OE_PHASE_EXT__SHFT                                                        (  0x00000010 )
#define DDR_DFICH_CTRL3_M0_CFG__ADR                                                                          (  0x00000080 )
#define DDR_DFICH_CTRL3_M0_CFG__WIDTH                                                                        (  22 )
#define DDR_DFICH_CTRL3_M0_CFG__POR                                                                          (  0x00020200 )
#define DDR_DFICH_CTRL3_M0_CFG__MSK                                                                          (  0x003F3F3F )


// Word Address 0x00000084 : DDR_DFICH_CTRL3_M1_CFG (RW)
#define DDR_DFICH_CTRL3_M1_CFG_WRD_CS_PHASE_EXT__MSK                                                         (  0x0000003F )
#define DDR_DFICH_CTRL3_M1_CFG_WRD_CS_PHASE_EXT__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_CTRL3_M1_CFG_WRD_EN_PHASE_EXT__MSK                                                         (  0x00003F00 )
#define DDR_DFICH_CTRL3_M1_CFG_WRD_EN_PHASE_EXT__SHFT                                                        (  0x00000008 )
#define DDR_DFICH_CTRL3_M1_CFG_WRD_OE_PHASE_EXT__MSK                                                         (  0x003F0000 )
#define DDR_DFICH_CTRL3_M1_CFG_WRD_OE_PHASE_EXT__SHFT                                                        (  0x00000010 )
#define DDR_DFICH_CTRL3_M1_CFG__ADR                                                                          (  0x00000084 )
#define DDR_DFICH_CTRL3_M1_CFG__WIDTH                                                                        (  22 )
#define DDR_DFICH_CTRL3_M1_CFG__POR                                                                          (  0x00020200 )
#define DDR_DFICH_CTRL3_M1_CFG__MSK                                                                          (  0x003F3F3F )


// Word Address 0x00000088 : DDR_DFICH_CTRL4_M0_CFG (RW)
#define DDR_DFICH_CTRL4_M0_CFG_WCK_OE_PHASE_EXT__MSK                                                         (  0x0000003F )
#define DDR_DFICH_CTRL4_M0_CFG_WCK_OE_PHASE_EXT__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_CTRL4_M0_CFG_WCK_CS_PHASE_EXT__MSK                                                         (  0x00003F00 )
#define DDR_DFICH_CTRL4_M0_CFG_WCK_CS_PHASE_EXT__SHFT                                                        (  0x00000008 )
#define DDR_DFICH_CTRL4_M0_CFG__ADR                                                                          (  0x00000088 )
#define DDR_DFICH_CTRL4_M0_CFG__WIDTH                                                                        (  14 )
#define DDR_DFICH_CTRL4_M0_CFG__POR                                                                          (  0x00000002 )
#define DDR_DFICH_CTRL4_M0_CFG__MSK                                                                          (  0x00003F3F )


// Word Address 0x0000008c : DDR_DFICH_CTRL4_M1_CFG (RW)
#define DDR_DFICH_CTRL4_M1_CFG_WCK_OE_PHASE_EXT__MSK                                                         (  0x0000003F )
#define DDR_DFICH_CTRL4_M1_CFG_WCK_OE_PHASE_EXT__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_CTRL4_M1_CFG_WCK_CS_PHASE_EXT__MSK                                                         (  0x00003F00 )
#define DDR_DFICH_CTRL4_M1_CFG_WCK_CS_PHASE_EXT__SHFT                                                        (  0x00000008 )
#define DDR_DFICH_CTRL4_M1_CFG__ADR                                                                          (  0x0000008c )
#define DDR_DFICH_CTRL4_M1_CFG__WIDTH                                                                        (  14 )
#define DDR_DFICH_CTRL4_M1_CFG__POR                                                                          (  0x00000002 )
#define DDR_DFICH_CTRL4_M1_CFG__MSK                                                                          (  0x00003F3F )


// Word Address 0x00000090 : DDR_DFICH_CTRL5_M0_CFG (RW)
#define DDR_DFICH_CTRL5_M0_CFG_RCS_PHASE_EXT__MSK                                                            (  0x0000003F )
#define DDR_DFICH_CTRL5_M0_CFG_RCS_PHASE_EXT__SHFT                                                           (  0x00000000 )
#define DDR_DFICH_CTRL5_M0_CFG_IE_PHASE_EXT__MSK                                                             (  0x00003F00 )
#define DDR_DFICH_CTRL5_M0_CFG_IE_PHASE_EXT__SHFT                                                            (  0x00000008 )
#define DDR_DFICH_CTRL5_M0_CFG_RE_PHASE_EXT__MSK                                                             (  0x003F0000 )
#define DDR_DFICH_CTRL5_M0_CFG_RE_PHASE_EXT__SHFT                                                            (  0x00000010 )
#define DDR_DFICH_CTRL5_M0_CFG_REN_PHASE_EXT__MSK                                                            (  0x3F000000 )
#define DDR_DFICH_CTRL5_M0_CFG_REN_PHASE_EXT__SHFT                                                           (  0x00000018 )
#define DDR_DFICH_CTRL5_M0_CFG__ADR                                                                          (  0x00000090 )
#define DDR_DFICH_CTRL5_M0_CFG__WIDTH                                                                        (  30 )
#define DDR_DFICH_CTRL5_M0_CFG__POR                                                                          (  0x00000000 )
#define DDR_DFICH_CTRL5_M0_CFG__MSK                                                                          (  0x3F3F3F3F )


// Word Address 0x00000094 : DDR_DFICH_CTRL5_M1_CFG (RW)
#define DDR_DFICH_CTRL5_M1_CFG_RCS_PHASE_EXT__MSK                                                            (  0x0000003F )
#define DDR_DFICH_CTRL5_M1_CFG_RCS_PHASE_EXT__SHFT                                                           (  0x00000000 )
#define DDR_DFICH_CTRL5_M1_CFG_IE_PHASE_EXT__MSK                                                             (  0x00003F00 )
#define DDR_DFICH_CTRL5_M1_CFG_IE_PHASE_EXT__SHFT                                                            (  0x00000008 )
#define DDR_DFICH_CTRL5_M1_CFG_RE_PHASE_EXT__MSK                                                             (  0x003F0000 )
#define DDR_DFICH_CTRL5_M1_CFG_RE_PHASE_EXT__SHFT                                                            (  0x00000010 )
#define DDR_DFICH_CTRL5_M1_CFG_REN_PHASE_EXT__MSK                                                            (  0x3F000000 )
#define DDR_DFICH_CTRL5_M1_CFG_REN_PHASE_EXT__SHFT                                                           (  0x00000018 )
#define DDR_DFICH_CTRL5_M1_CFG__ADR                                                                          (  0x00000094 )
#define DDR_DFICH_CTRL5_M1_CFG__WIDTH                                                                        (  30 )
#define DDR_DFICH_CTRL5_M1_CFG__POR                                                                          (  0x00000000 )
#define DDR_DFICH_CTRL5_M1_CFG__MSK                                                                          (  0x3F3F3F3F )


// Word Address 0x00000098 : DDR_DFICH_MISR_0_CFG (RW)
#define DDR_DFICH_MISR_0_CFG_LFSR_CLEAR__MSK                                                                 (  0x00000001 )
#define DDR_DFICH_MISR_0_CFG_LFSR_CLEAR__SHFT                                                                (  0x00000000 )
#define DDR_DFICH_MISR_0_CFG_LFSR_LD_SEED__MSK                                                               (  0x00000002 )
#define DDR_DFICH_MISR_0_CFG_LFSR_LD_SEED__SHFT                                                              (  0x00000001 )
#define DDR_DFICH_MISR_0_CFG_MISR_ENABLE__MSK                                                                (  0x000001F0 )
#define DDR_DFICH_MISR_0_CFG_MISR_ENABLE__SHFT                                                               (  0x00000004 )
#define DDR_DFICH_MISR_0_CFG__ADR                                                                            (  0x00000098 )
#define DDR_DFICH_MISR_0_CFG__WIDTH                                                                          (   9 )
#define DDR_DFICH_MISR_0_CFG__POR                                                                            (  0x00000000 )
#define DDR_DFICH_MISR_0_CFG__MSK                                                                            (  0x000001F3 )


// Word Address 0x0000009c : DDR_DFICH_MISR_1_CFG (RW)
#define DDR_DFICH_MISR_1_CFG_LFSR_SEED_LO__MSK                                                               (  0xFFFFFFFF )
#define DDR_DFICH_MISR_1_CFG_LFSR_SEED_LO__SHFT                                                              (  0x00000000 )
#define DDR_DFICH_MISR_1_CFG__ADR                                                                            (  0x0000009c )
#define DDR_DFICH_MISR_1_CFG__WIDTH                                                                          (  32 )
#define DDR_DFICH_MISR_1_CFG__POR                                                                            (  0x00000000 )
#define DDR_DFICH_MISR_1_CFG__MSK                                                                            (  0xFFFFFFFF )


// Word Address 0x000000a0 : DDR_DFICH_MISR_2_CFG (RW)
#define DDR_DFICH_MISR_2_CFG_LFSR_SEED_HI__MSK                                                               (  0x0000000F )
#define DDR_DFICH_MISR_2_CFG_LFSR_SEED_HI__SHFT                                                              (  0x00000000 )
#define DDR_DFICH_MISR_2_CFG__ADR                                                                            (  0x000000a0 )
#define DDR_DFICH_MISR_2_CFG__WIDTH                                                                          (   4 )
#define DDR_DFICH_MISR_2_CFG__POR                                                                            (  0x00000000 )
#define DDR_DFICH_MISR_2_CFG__MSK                                                                            (  0x0000000F )


// Word Address 0x000000a4 : DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA (R)
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA__ADR                                                              (  0x000000a4 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000a8 : DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA (R)
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA__ADR                                                              (  0x000000a8 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ0_W3_TO_W0_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000ac : DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA (R)
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA__ADR                                                              (  0x000000ac )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000b0 : DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA (R)
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA__ADR                                                              (  0x000000b0 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ0_W7_TO_W4_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000b4 : DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA (R)
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA__ADR                                                              (  0x000000b4 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000b8 : DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA (R)
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA__ADR                                                              (  0x000000b8 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ1_W3_TO_W0_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000bc : DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA (R)
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA__ADR                                                              (  0x000000bc )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000c0 : DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA (R)
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA__ADR                                                              (  0x000000c0 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ1_W7_TO_W4_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000c4 : DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA (R)
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA__ADR                                                              (  0x000000c4 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000c8 : DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA (R)
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA__ADR                                                              (  0x000000c8 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ2_W3_TO_W0_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000cc : DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA (R)
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA__ADR                                                              (  0x000000cc )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000d0 : DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA (R)
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA__ADR                                                              (  0x000000d0 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ2_W7_TO_W4_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000d4 : DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA (R)
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA__ADR                                                              (  0x000000d4 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000d8 : DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA (R)
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA__ADR                                                              (  0x000000d8 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ3_W3_TO_W0_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000dc : DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA (R)
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA_DATA__MSK                                                         (  0xFFFFFFFF )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA__ADR                                                              (  0x000000dc )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA__WIDTH                                                            (  32 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_LO_STA__MSK                                                              (  0xFFFFFFFF )


// Word Address 0x000000e0 : DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA (R)
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA_DATA__MSK                                                         (  0x000000FF )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA_DATA__SHFT                                                        (  0x00000000 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA__ADR                                                              (  0x000000e0 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA__WIDTH                                                            (   8 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA__POR                                                              (  0x00000000 )
#define DDR_DFICH_DQ3_W7_TO_W4_MISR_HI_STA__MSK                                                              (  0x000000FF )


// Word Address 0x000000e4 : DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA (R)
#define DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA_DATA__MSK                                                          (  0xFFFFFFFF )
#define DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA__ADR                                                               (  0x000000e4 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA__WIDTH                                                             (  32 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_LO_STA__MSK                                                               (  0xFFFFFFFF )


// Word Address 0x000000e8 : DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA (R)
#define DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA_DATA__MSK                                                          (  0x000000FF )
#define DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA__ADR                                                               (  0x000000e8 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA__WIDTH                                                             (   8 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W1_TO_W0_MISR_HI_STA__MSK                                                               (  0x000000FF )


// Word Address 0x000000ec : DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA (R)
#define DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA_DATA__MSK                                                          (  0xFFFFFFFF )
#define DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA__ADR                                                               (  0x000000ec )
#define DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA__WIDTH                                                             (  32 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_LO_STA__MSK                                                               (  0xFFFFFFFF )


// Word Address 0x000000f0 : DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA (R)
#define DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA_DATA__MSK                                                          (  0x000000FF )
#define DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA__ADR                                                               (  0x000000f0 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA__WIDTH                                                             (   8 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W3_TO_W2_MISR_HI_STA__MSK                                                               (  0x000000FF )


// Word Address 0x000000f4 : DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA (R)
#define DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA_DATA__MSK                                                          (  0xFFFFFFFF )
#define DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA__ADR                                                               (  0x000000f4 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA__WIDTH                                                             (  32 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_LO_STA__MSK                                                               (  0xFFFFFFFF )


// Word Address 0x000000f8 : DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA (R)
#define DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA_DATA__MSK                                                          (  0x000000FF )
#define DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA__ADR                                                               (  0x000000f8 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA__WIDTH                                                             (   8 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W5_TO_W4_MISR_HI_STA__MSK                                                               (  0x000000FF )


// Word Address 0x000000fc : DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA (R)
#define DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA_DATA__MSK                                                          (  0xFFFFFFFF )
#define DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA__ADR                                                               (  0x000000fc )
#define DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA__WIDTH                                                             (  32 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_LO_STA__MSK                                                               (  0xFFFFFFFF )


// Word Address 0x00000100 : DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA (R)
#define DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA_DATA__MSK                                                          (  0x000000FF )
#define DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA_DATA__SHFT                                                         (  0x00000000 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA__ADR                                                               (  0x00000100 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA__WIDTH                                                             (   8 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA__POR                                                               (  0x00000000 )
#define DDR_DFICH_CA_W7_TO_W6_MISR_HI_STA__MSK                                                               (  0x000000FF )


#endif /* _DDR_DFICH_CSR_H_ */
