/**
 * Copyright (c) 2021 Wavious LLC.
 *
 * SPDX-License-Identifier: GPL-3.0
 */
// MODULE MVP_PLL
// RANGE 0x00:0x00
// WIDTH 32

#ifndef _DDR_MVP_PLL_CSR_H_
#define _DDR_MVP_PLL_CSR_H_

// Word Address 0x00000000 : DDR_MVP_PLL_CORE_OVERRIDES (RW)
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_RESET__MSK                                                           (  0x00000001 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_RESET__SHFT                                                          (  0x00000000 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_RESET_MUX__MSK                                                       (  0x00000002 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_RESET_MUX__SHFT                                                      (  0x00000001 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_VCO_SEL__MSK                                                         (  0x0000000C )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_VCO_SEL__SHFT                                                        (  0x00000002 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_VCO_SEL_MUX__MSK                                                     (  0x00000010 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_VCO_SEL_MUX__SHFT                                                    (  0x00000004 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_GFCM_SEL__MSK                                                        (  0x00000020 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_GFCM_SEL__SHFT                                                       (  0x00000005 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_GFCM_SEL_MUX__MSK                                                    (  0x00000040 )
#define DDR_MVP_PLL_CORE_OVERRIDES_CORE_GFCM_SEL_MUX__SHFT                                                   (  0x00000006 )
#define DDR_MVP_PLL_CORE_OVERRIDES__ADR                                                                      (  0x00000000 )
#define DDR_MVP_PLL_CORE_OVERRIDES__WIDTH                                                                    (   7 )
#define DDR_MVP_PLL_CORE_OVERRIDES__POR                                                                      (  0x00000000 )
#define DDR_MVP_PLL_CORE_OVERRIDES__MSK                                                                      (  0x0000007F )


// Word Address 0x00000004 : DDR_MVP_PLL_CORE_SWTICH_VCO (RW)
#define DDR_MVP_PLL_CORE_SWTICH_VCO_CORE_SWITCH_VCO__MSK                                                     (  0x00000001 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_CORE_SWITCH_VCO__SHFT                                                    (  0x00000000 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO__ADR                                                                     (  0x00000004 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO__WIDTH                                                                   (   1 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO__POR                                                                     (  0x00000000 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO__MSK                                                                     (  0x00000001 )


// Word Address 0x00000008 : DDR_MVP_PLL_CORE_SWTICH_VCO_HW (RW)
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW_CORE_SWITCH_VCO_HW__MSK                                               (  0x00000001 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW_CORE_SWITCH_VCO_HW__SHFT                                              (  0x00000000 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW_CORE_SWITCH_VCO_HW_MUX__MSK                                           (  0x00000002 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW_CORE_SWITCH_VCO_HW_MUX__SHFT                                          (  0x00000001 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW__ADR                                                                  (  0x00000008 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW__WIDTH                                                                (   2 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW__POR                                                                  (  0x00000000 )
#define DDR_MVP_PLL_CORE_SWTICH_VCO_HW__MSK                                                                  (  0x00000003 )


// Word Address 0x0000000c : DDR_MVP_PLL_CORE_STATUS (R)
#define DDR_MVP_PLL_CORE_STATUS_CORE_READY__MSK                                                              (  0x00000001 )
#define DDR_MVP_PLL_CORE_STATUS_CORE_READY__SHFT                                                             (  0x00000000 )
#define DDR_MVP_PLL_CORE_STATUS_CORE_FASTLOCK_READY__MSK                                                     (  0x00000002 )
#define DDR_MVP_PLL_CORE_STATUS_CORE_FASTLOCK_READY__SHFT                                                    (  0x00000001 )
#define DDR_MVP_PLL_CORE_STATUS_CORE_INITIAL_SWITCH_DONE__MSK                                                (  0x00000004 )
#define DDR_MVP_PLL_CORE_STATUS_CORE_INITIAL_SWITCH_DONE__SHFT                                               (  0x00000002 )
#define DDR_MVP_PLL_CORE_STATUS_FREQ_DETECT_LOCK__MSK                                                        (  0x00000008 )
#define DDR_MVP_PLL_CORE_STATUS_FREQ_DETECT_LOCK__SHFT                                                       (  0x00000003 )
#define DDR_MVP_PLL_CORE_STATUS_FREQ_DETECT_CYCLES__MSK                                                      (  0x001FFFF0 )
#define DDR_MVP_PLL_CORE_STATUS_FREQ_DETECT_CYCLES__SHFT                                                     (  0x00000004 )
#define DDR_MVP_PLL_CORE_STATUS_FSM_STATE__MSK                                                               (  0x01E00000 )
#define DDR_MVP_PLL_CORE_STATUS_FSM_STATE__SHFT                                                              (  0x00000015 )
#define DDR_MVP_PLL_CORE_STATUS__ADR                                                                         (  0x0000000c )
#define DDR_MVP_PLL_CORE_STATUS__WIDTH                                                                       (  25 )
#define DDR_MVP_PLL_CORE_STATUS__POR                                                                         (  0x00000000 )
#define DDR_MVP_PLL_CORE_STATUS__MSK                                                                         (  0x01FFFFFF )


// Word Address 0x00000010 : DDR_MVP_PLL_CORE_STATUS_INT (R)
#define DDR_MVP_PLL_CORE_STATUS_INT_LOSS_OF_LOCK__MSK                                                        (  0x00000001 )
#define DDR_MVP_PLL_CORE_STATUS_INT_LOSS_OF_LOCK__SHFT                                                       (  0x00000000 )
#define DDR_MVP_PLL_CORE_STATUS_INT_CORE_LOCKED__MSK                                                         (  0x00000002 )
#define DDR_MVP_PLL_CORE_STATUS_INT_CORE_LOCKED__SHFT                                                        (  0x00000001 )
#define DDR_MVP_PLL_CORE_STATUS_INT_INITIAL_SWITCH_DONE__MSK                                                 (  0x00000004 )
#define DDR_MVP_PLL_CORE_STATUS_INT_INITIAL_SWITCH_DONE__SHFT                                                (  0x00000002 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO0_FLL_LOCKED__MSK                                                     (  0x00000008 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO0_FLL_LOCKED__SHFT                                                    (  0x00000003 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO0_FLL_THRESHOLD__MSK                                                  (  0x00000010 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO0_FLL_THRESHOLD__SHFT                                                 (  0x00000004 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO1_FLL_LOCKED__MSK                                                     (  0x00000020 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO1_FLL_LOCKED__SHFT                                                    (  0x00000005 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO1_FLL_THRESHOLD__MSK                                                  (  0x00000040 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO1_FLL_THRESHOLD__SHFT                                                 (  0x00000006 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO2_FLL_LOCKED__MSK                                                     (  0x00000080 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO2_FLL_LOCKED__SHFT                                                    (  0x00000007 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO2_FLL_THRESHOLD__MSK                                                  (  0x00000100 )
#define DDR_MVP_PLL_CORE_STATUS_INT_VCO2_FLL_THRESHOLD__SHFT                                                 (  0x00000008 )
#define DDR_MVP_PLL_CORE_STATUS_INT__ADR                                                                     (  0x00000010 )
#define DDR_MVP_PLL_CORE_STATUS_INT__WIDTH                                                                   (   9 )
#define DDR_MVP_PLL_CORE_STATUS_INT__POR                                                                     (  0x00000000 )
#define DDR_MVP_PLL_CORE_STATUS_INT__MSK                                                                     (  0x000001FF )


// Word Address 0x00000014 : DDR_MVP_PLL_CORE_STATUS_INT_EN (RW)
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_LOSS_OF_LOCK_INT_EN__MSK                                              (  0x00000001 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_LOSS_OF_LOCK_INT_EN__SHFT                                             (  0x00000000 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_CORE_LOCKED_INT_EN__MSK                                               (  0x00000002 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_CORE_LOCKED_INT_EN__SHFT                                              (  0x00000001 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_INITIAL_SWITCH_DONE_INT_EN__MSK                                       (  0x00000004 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_INITIAL_SWITCH_DONE_INT_EN__SHFT                                      (  0x00000002 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO0_FLL_LOCKED_INT_EN__MSK                                           (  0x00000008 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO0_FLL_LOCKED_INT_EN__SHFT                                          (  0x00000003 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO0_FLL_THRESHOLD_INT_EN__MSK                                        (  0x00000010 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO0_FLL_THRESHOLD_INT_EN__SHFT                                       (  0x00000004 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO1_FLL_LOCKED_INT_EN__MSK                                           (  0x00000020 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO1_FLL_LOCKED_INT_EN__SHFT                                          (  0x00000005 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO1_FLL_THRESHOLD_INT_EN__MSK                                        (  0x00000040 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO1_FLL_THRESHOLD_INT_EN__SHFT                                       (  0x00000006 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO2_FLL_LOCKED_INT_EN__MSK                                           (  0x00000080 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO2_FLL_LOCKED_INT_EN__SHFT                                          (  0x00000007 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO2_FLL_THRESHOLD_INT_EN__MSK                                        (  0x00000100 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN_VCO2_FLL_THRESHOLD_INT_EN__SHFT                                       (  0x00000008 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN__ADR                                                                  (  0x00000014 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN__WIDTH                                                                (   9 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN__POR                                                                  (  0x00000000 )
#define DDR_MVP_PLL_CORE_STATUS_INT_EN__MSK                                                                  (  0x000001FF )


// Word Address 0x00000018 : DDR_MVP_PLL_VCO0_BAND (RW)
#define DDR_MVP_PLL_VCO0_BAND_VCO0_BAND__MSK                                                                 (  0x0000003F )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_BAND__SHFT                                                                (  0x00000000 )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_BAND_MUX__MSK                                                             (  0x00000040 )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_BAND_MUX__SHFT                                                            (  0x00000006 )
#define DDR_MVP_PLL_VCO0_BAND_RESERVED__MSK                                                                  (  0x00000080 )
#define DDR_MVP_PLL_VCO0_BAND_RESERVED__SHFT                                                                 (  0x00000007 )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_FINE__MSK                                                                 (  0x00003F00 )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_FINE__SHFT                                                                (  0x00000008 )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_FINE_MUX__MSK                                                             (  0x00004000 )
#define DDR_MVP_PLL_VCO0_BAND_VCO0_FINE_MUX__SHFT                                                            (  0x0000000E )
#define DDR_MVP_PLL_VCO0_BAND__ADR                                                                           (  0x00000018 )
#define DDR_MVP_PLL_VCO0_BAND__WIDTH                                                                         (  15 )
#define DDR_MVP_PLL_VCO0_BAND__POR                                                                           (  0x00005F40 )
#define DDR_MVP_PLL_VCO0_BAND__MSK                                                                           (  0x00007FFF )


// Word Address 0x0000001c : DDR_MVP_PLL_VCO0_CONTROL (RW)
#define DDR_MVP_PLL_VCO0_CONTROL_VCO0_ENA__MSK                                                               (  0x00000001 )
#define DDR_MVP_PLL_VCO0_CONTROL_VCO0_ENA__SHFT                                                              (  0x00000000 )
#define DDR_MVP_PLL_VCO0_CONTROL_VCO0_ENA_MUX__MSK                                                           (  0x00000002 )
#define DDR_MVP_PLL_VCO0_CONTROL_VCO0_ENA_MUX__SHFT                                                          (  0x00000001 )
#define DDR_MVP_PLL_VCO0_CONTROL_VCO0_BYP_CLK_SEL__MSK                                                       (  0x00000004 )
#define DDR_MVP_PLL_VCO0_CONTROL_VCO0_BYP_CLK_SEL__SHFT                                                      (  0x00000002 )
#define DDR_MVP_PLL_VCO0_CONTROL__ADR                                                                        (  0x0000001c )
#define DDR_MVP_PLL_VCO0_CONTROL__WIDTH                                                                      (   3 )
#define DDR_MVP_PLL_VCO0_CONTROL__POR                                                                        (  0x00000000 )
#define DDR_MVP_PLL_VCO0_CONTROL__MSK                                                                        (  0x00000007 )


// Word Address 0x00000020 : DDR_MVP_PLL_VCO0_FLL_CONTROL1 (RW)
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_ENABLE__MSK                                                   (  0x00000001 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_ENABLE__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_MANUAL_MODE__MSK                                              (  0x00000002 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_MANUAL_MODE__SHFT                                             (  0x00000001 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_BAND_START__MSK                                                   (  0x000000FC )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_BAND_START__SHFT                                                  (  0x00000002 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FINE_START__MSK                                                   (  0x00003F00 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FINE_START__SHFT                                                  (  0x00000008 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_DELAY_COUNT__MSK                                                  (  0x0003C000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_DELAY_COUNT__SHFT                                                 (  0x0000000E )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_USE_DEMETED_CHECK__MSK                                            (  0x00040000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_USE_DEMETED_CHECK__SHFT                                           (  0x00000012 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_LOCKED_COUNT_THRESHOLD__MSK                                       (  0x00780000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_LOCKED_COUNT_THRESHOLD__SHFT                                      (  0x00000013 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_BYPASS_BAND__MSK                                              (  0x00800000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_BYPASS_BAND__SHFT                                             (  0x00000017 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_BYPASS_FINE__MSK                                              (  0x01000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_BYPASS_FINE__SHFT                                             (  0x00000018 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_PERSISTENT_MODE__MSK                                          (  0x02000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_FLL_PERSISTENT_MODE__SHFT                                         (  0x00000019 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_TOO_FAST_STATUS__MSK                                              (  0x04000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_TOO_FAST_STATUS__SHFT                                             (  0x0000001A )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_TOO_SLOW_STATUS__MSK                                              (  0x08000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_TOO_SLOW_STATUS__SHFT                                             (  0x0000001B )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_LOCKED__MSK                                                       (  0x10000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1_VCO0_LOCKED__SHFT                                                      (  0x0000001C )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1__ADR                                                                   (  0x00000020 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1__WIDTH                                                                 (  29 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1__POR                                                                   (  0x02A49F7C )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL1__MSK                                                                   (  0x1FFFFFFF )


// Word Address 0x00000024 : DDR_MVP_PLL_VCO0_FLL_CONTROL2 (RW)
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2_VCO0_FLL_REFCLK_COUNT__MSK                                             (  0x000000FF )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2_VCO0_FLL_REFCLK_COUNT__SHFT                                            (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2_VCO0_FLL_VCO_COUNT_TARGET__MSK                                         (  0x00FFFF00 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2_VCO0_FLL_VCO_COUNT_TARGET__SHFT                                        (  0x00000008 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2_VCO0_FLL_RANGE__MSK                                                    (  0x1F000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2_VCO0_FLL_RANGE__SHFT                                                   (  0x00000018 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2__ADR                                                                   (  0x00000024 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2__WIDTH                                                                 (  29 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2__POR                                                                   (  0x0400D008 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL2__MSK                                                                   (  0x1FFFFFFF )


// Word Address 0x00000028 : DDR_MVP_PLL_VCO0_FLL_CONTROL3 (RW)
#define DDR_MVP_PLL_VCO0_FLL_CONTROL3_VCO0_FLL_BAND_THRESH__MSK                                              (  0x0000003F )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL3_VCO0_FLL_BAND_THRESH__SHFT                                             (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL3__ADR                                                                   (  0x00000028 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL3__WIDTH                                                                 (   6 )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL3__POR                                                                   (  0x0000003C )
#define DDR_MVP_PLL_VCO0_FLL_CONTROL3__MSK                                                                   (  0x0000003F )


// Word Address 0x0000002c : DDR_MVP_PLL_VCO0_FLL_BAND_STATUS (R)
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_BAND_STATUS__MSK                                               (  0x0000003F )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_BAND_STATUS__SHFT                                              (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_BAND_PREV_STATUS__MSK                                          (  0x00000FC0 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_BAND_PREV_STATUS__SHFT                                         (  0x00000006 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_FINE_STATUS__MSK                                               (  0x0003F000 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_FINE_STATUS__SHFT                                              (  0x0000000C )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_FINE_PREV_STATUS__MSK                                          (  0x00FC0000 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS_VCO0_FINE_PREV_STATUS__SHFT                                         (  0x00000012 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS__ADR                                                                (  0x0000002c )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS__WIDTH                                                              (  24 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS__POR                                                                (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_BAND_STATUS__MSK                                                                (  0x00FFFFFF )


// Word Address 0x00000030 : DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS (R)
#define DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS_VCO0_VCO_COUNT__MSK                                                (  0x0000FFFF )
#define DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS_VCO0_VCO_COUNT__SHFT                                               (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS__ADR                                                               (  0x00000030 )
#define DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS__WIDTH                                                             (  16 )
#define DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS__POR                                                               (  0x00000000 )
#define DDR_MVP_PLL_VCO0_FLL_COUNT_STATUS__MSK                                                               (  0x0000FFFF )


// Word Address 0x00000034 : DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS (RW)
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_INT__MSK                                                     (  0x000001FF )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_INT__SHFT                                                    (  0x00000000 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_FRAC__MSK                                                    (  0x01FFFE00 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_FRAC__SHFT                                                   (  0x00000009 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_FRAC_EN__MSK                                                 (  0x02000000 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_FRAC_EN__SHFT                                                (  0x00000019 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_FRAC_EN_AUTO__MSK                                            (  0x04000000 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS_VCO0_FRAC_EN_AUTO__SHFT                                           (  0x0000001A )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS__ADR                                                              (  0x00000034 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS__WIDTH                                                            (  27 )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS__POR                                                              (  0x0400000A )
#define DDR_MVP_PLL_VCO0_INT_FRAC_SETTINGS__MSK                                                              (  0x07FFFFFF )


// Word Address 0x00000038 : DDR_MVP_PLL_VCO0_PROP_GAINS (RW)
#define DDR_MVP_PLL_VCO0_PROP_GAINS_VCO0_PROP_GAIN__MSK                                                      (  0x0000001F )
#define DDR_MVP_PLL_VCO0_PROP_GAINS_VCO0_PROP_GAIN__SHFT                                                     (  0x00000000 )
#define DDR_MVP_PLL_VCO0_PROP_GAINS__ADR                                                                     (  0x00000038 )
#define DDR_MVP_PLL_VCO0_PROP_GAINS__WIDTH                                                                   (   5 )
#define DDR_MVP_PLL_VCO0_PROP_GAINS__POR                                                                     (  0x0000000A )
#define DDR_MVP_PLL_VCO0_PROP_GAINS__MSK                                                                     (  0x0000001F )


// Word Address 0x0000003c : DDR_MVP_PLL_VCO1_BAND (RW)
#define DDR_MVP_PLL_VCO1_BAND_VCO1_BAND__MSK                                                                 (  0x0000003F )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_BAND__SHFT                                                                (  0x00000000 )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_BAND_MUX__MSK                                                             (  0x00000040 )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_BAND_MUX__SHFT                                                            (  0x00000006 )
#define DDR_MVP_PLL_VCO1_BAND_RESERVED__MSK                                                                  (  0x00000080 )
#define DDR_MVP_PLL_VCO1_BAND_RESERVED__SHFT                                                                 (  0x00000007 )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_FINE__MSK                                                                 (  0x00003F00 )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_FINE__SHFT                                                                (  0x00000008 )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_FINE_MUX__MSK                                                             (  0x00004000 )
#define DDR_MVP_PLL_VCO1_BAND_VCO1_FINE_MUX__SHFT                                                            (  0x0000000E )
#define DDR_MVP_PLL_VCO1_BAND__ADR                                                                           (  0x0000003c )
#define DDR_MVP_PLL_VCO1_BAND__WIDTH                                                                         (  15 )
#define DDR_MVP_PLL_VCO1_BAND__POR                                                                           (  0x00000000 )
#define DDR_MVP_PLL_VCO1_BAND__MSK                                                                           (  0x00007FFF )


// Word Address 0x00000040 : DDR_MVP_PLL_VCO1_CONTROL (RW)
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_ENA__MSK                                                               (  0x00000001 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_ENA__SHFT                                                              (  0x00000000 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_ENA_MUX__MSK                                                           (  0x00000002 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_ENA_MUX__SHFT                                                          (  0x00000001 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_BYP_CLK_SEL__MSK                                                       (  0x00000004 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_BYP_CLK_SEL__SHFT                                                      (  0x00000002 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_POST_DIV__MSK                                                          (  0x00000018 )
#define DDR_MVP_PLL_VCO1_CONTROL_VCO1_POST_DIV__SHFT                                                         (  0x00000003 )
#define DDR_MVP_PLL_VCO1_CONTROL__ADR                                                                        (  0x00000040 )
#define DDR_MVP_PLL_VCO1_CONTROL__WIDTH                                                                      (   5 )
#define DDR_MVP_PLL_VCO1_CONTROL__POR                                                                        (  0x00000000 )
#define DDR_MVP_PLL_VCO1_CONTROL__MSK                                                                        (  0x0000001F )


// Word Address 0x00000044 : DDR_MVP_PLL_VCO1_FLL_CONTROL1 (RW)
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_ENABLE__MSK                                                   (  0x00000001 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_ENABLE__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_MANUAL_MODE__MSK                                              (  0x00000002 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_MANUAL_MODE__SHFT                                             (  0x00000001 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_BAND_START__MSK                                                   (  0x000000FC )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_BAND_START__SHFT                                                  (  0x00000002 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FINE_START__MSK                                                   (  0x00003F00 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FINE_START__SHFT                                                  (  0x00000008 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_DELAY_COUNT__MSK                                                  (  0x0003C000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_DELAY_COUNT__SHFT                                                 (  0x0000000E )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_USE_DEMETED_CHECK__MSK                                            (  0x00040000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_USE_DEMETED_CHECK__SHFT                                           (  0x00000012 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_LOCKED_COUNT_THRESHOLD__MSK                                       (  0x00780000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_LOCKED_COUNT_THRESHOLD__SHFT                                      (  0x00000013 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_BYPASS_BAND__MSK                                              (  0x00800000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_BYPASS_BAND__SHFT                                             (  0x00000017 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_BYPASS_FINE__MSK                                              (  0x01000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_BYPASS_FINE__SHFT                                             (  0x00000018 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_PERSISTENT_MODE__MSK                                          (  0x02000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_FLL_PERSISTENT_MODE__SHFT                                         (  0x00000019 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_TOO_FAST_STATUS__MSK                                              (  0x04000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_TOO_FAST_STATUS__SHFT                                             (  0x0000001A )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_TOO_SLOW_STATUS__MSK                                              (  0x08000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_TOO_SLOW_STATUS__SHFT                                             (  0x0000001B )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_LOCKED__MSK                                                       (  0x10000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1_VCO1_LOCKED__SHFT                                                      (  0x0000001C )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1__ADR                                                                   (  0x00000044 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1__WIDTH                                                                 (  29 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1__POR                                                                   (  0x00249F00 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL1__MSK                                                                   (  0x1FFFFFFF )


// Word Address 0x00000048 : DDR_MVP_PLL_VCO1_FLL_CONTROL2 (RW)
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2_VCO1_FLL_REFCLK_COUNT__MSK                                             (  0x000000FF )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2_VCO1_FLL_REFCLK_COUNT__SHFT                                            (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2_VCO1_FLL_VCO_COUNT_TARGET__MSK                                         (  0x00FFFF00 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2_VCO1_FLL_VCO_COUNT_TARGET__SHFT                                        (  0x00000008 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2_VCO1_FLL_RANGE__MSK                                                    (  0x1F000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2_VCO1_FLL_RANGE__SHFT                                                   (  0x00000018 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2__ADR                                                                   (  0x00000048 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2__WIDTH                                                                 (  29 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2__POR                                                                   (  0x0400D008 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL2__MSK                                                                   (  0x1FFFFFFF )


// Word Address 0x0000004c : DDR_MVP_PLL_VCO1_FLL_CONTROL3 (RW)
#define DDR_MVP_PLL_VCO1_FLL_CONTROL3_VCO1_FLL_BAND_THRESH__MSK                                              (  0x0000003F )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL3_VCO1_FLL_BAND_THRESH__SHFT                                             (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL3__ADR                                                                   (  0x0000004c )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL3__WIDTH                                                                 (   6 )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL3__POR                                                                   (  0x0000003C )
#define DDR_MVP_PLL_VCO1_FLL_CONTROL3__MSK                                                                   (  0x0000003F )


// Word Address 0x00000050 : DDR_MVP_PLL_VCO1_FLL_BAND_STATUS (R)
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_BAND_STATUS__MSK                                               (  0x0000003F )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_BAND_STATUS__SHFT                                              (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_BAND_PREV_STATUS__MSK                                          (  0x00000FC0 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_BAND_PREV_STATUS__SHFT                                         (  0x00000006 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_FINE_STATUS__MSK                                               (  0x0003F000 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_FINE_STATUS__SHFT                                              (  0x0000000C )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_FINE_PREV_STATUS__MSK                                          (  0x00FC0000 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS_VCO1_FINE_PREV_STATUS__SHFT                                         (  0x00000012 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS__ADR                                                                (  0x00000050 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS__WIDTH                                                              (  24 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS__POR                                                                (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_BAND_STATUS__MSK                                                                (  0x00FFFFFF )


// Word Address 0x00000054 : DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS (R)
#define DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS_VCO1_VCO_COUNT__MSK                                                (  0x0000FFFF )
#define DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS_VCO1_VCO_COUNT__SHFT                                               (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS__ADR                                                               (  0x00000054 )
#define DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS__WIDTH                                                             (  16 )
#define DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS__POR                                                               (  0x00000000 )
#define DDR_MVP_PLL_VCO1_FLL_COUNT_STATUS__MSK                                                               (  0x0000FFFF )


// Word Address 0x00000058 : DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS (RW)
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_INT__MSK                                                     (  0x000001FF )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_INT__SHFT                                                    (  0x00000000 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_FRAC__MSK                                                    (  0x01FFFE00 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_FRAC__SHFT                                                   (  0x00000009 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_FRAC_EN__MSK                                                 (  0x02000000 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_FRAC_EN__SHFT                                                (  0x00000019 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_FRAC_EN_AUTO__MSK                                            (  0x04000000 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS_VCO1_FRAC_EN_AUTO__SHFT                                           (  0x0000001A )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS__ADR                                                              (  0x00000058 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS__WIDTH                                                            (  27 )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS__POR                                                              (  0x0400000A )
#define DDR_MVP_PLL_VCO1_INT_FRAC_SETTINGS__MSK                                                              (  0x07FFFFFF )


// Word Address 0x0000005c : DDR_MVP_PLL_VCO1_PROP_GAINS (RW)
#define DDR_MVP_PLL_VCO1_PROP_GAINS_VCO1_PROP_GAIN__MSK                                                      (  0x0000001F )
#define DDR_MVP_PLL_VCO1_PROP_GAINS_VCO1_PROP_GAIN__SHFT                                                     (  0x00000000 )
#define DDR_MVP_PLL_VCO1_PROP_GAINS__ADR                                                                     (  0x0000005c )
#define DDR_MVP_PLL_VCO1_PROP_GAINS__WIDTH                                                                   (   5 )
#define DDR_MVP_PLL_VCO1_PROP_GAINS__POR                                                                     (  0x0000000A )
#define DDR_MVP_PLL_VCO1_PROP_GAINS__MSK                                                                     (  0x0000001F )


// Word Address 0x00000060 : DDR_MVP_PLL_VCO1_SSC_CONTROLS (RW)
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_ENABLE__MSK                                                   (  0x00000001 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_ENABLE__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_STEPSIZE__MSK                                                 (  0x000007FE )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_STEPSIZE__SHFT                                                (  0x00000001 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_AMP__MSK                                                      (  0x0FFFF800 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_AMP__SHFT                                                     (  0x0000000B )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_COUNT_CYCLES__MSK                                             (  0x10000000 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_COUNT_CYCLES__SHFT                                            (  0x0000001C )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_CENTER_SPREAD__MSK                                            (  0x20000000 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS_VCO1_SSC_CENTER_SPREAD__SHFT                                           (  0x0000001D )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS__ADR                                                                   (  0x00000060 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS__WIDTH                                                                 (  30 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS__POR                                                                   (  0x00000000 )
#define DDR_MVP_PLL_VCO1_SSC_CONTROLS__MSK                                                                   (  0x3FFFFFFF )


// Word Address 0x00000064 : DDR_MVP_PLL_VCO2_BAND (RW)
#define DDR_MVP_PLL_VCO2_BAND_VCO2_BAND__MSK                                                                 (  0x0000003F )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_BAND__SHFT                                                                (  0x00000000 )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_BAND_MUX__MSK                                                             (  0x00000040 )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_BAND_MUX__SHFT                                                            (  0x00000006 )
#define DDR_MVP_PLL_VCO2_BAND_RESERVED__MSK                                                                  (  0x00000080 )
#define DDR_MVP_PLL_VCO2_BAND_RESERVED__SHFT                                                                 (  0x00000007 )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_FINE__MSK                                                                 (  0x00003F00 )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_FINE__SHFT                                                                (  0x00000008 )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_FINE_MUX__MSK                                                             (  0x00004000 )
#define DDR_MVP_PLL_VCO2_BAND_VCO2_FINE_MUX__SHFT                                                            (  0x0000000E )
#define DDR_MVP_PLL_VCO2_BAND__ADR                                                                           (  0x00000064 )
#define DDR_MVP_PLL_VCO2_BAND__WIDTH                                                                         (  15 )
#define DDR_MVP_PLL_VCO2_BAND__POR                                                                           (  0x00000000 )
#define DDR_MVP_PLL_VCO2_BAND__MSK                                                                           (  0x00007FFF )


// Word Address 0x00000068 : DDR_MVP_PLL_VCO2_CONTROL (RW)
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_ENA__MSK                                                               (  0x00000001 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_ENA__SHFT                                                              (  0x00000000 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_ENA_MUX__MSK                                                           (  0x00000002 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_ENA_MUX__SHFT                                                          (  0x00000001 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_BYP_CLK_SEL__MSK                                                       (  0x00000004 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_BYP_CLK_SEL__SHFT                                                      (  0x00000002 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_POST_DIV__MSK                                                          (  0x00000018 )
#define DDR_MVP_PLL_VCO2_CONTROL_VCO2_POST_DIV__SHFT                                                         (  0x00000003 )
#define DDR_MVP_PLL_VCO2_CONTROL__ADR                                                                        (  0x00000068 )
#define DDR_MVP_PLL_VCO2_CONTROL__WIDTH                                                                      (   5 )
#define DDR_MVP_PLL_VCO2_CONTROL__POR                                                                        (  0x00000000 )
#define DDR_MVP_PLL_VCO2_CONTROL__MSK                                                                        (  0x0000001F )


// Word Address 0x0000006c : DDR_MVP_PLL_VCO2_FLL_CONTROL1 (RW)
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_ENABLE__MSK                                                   (  0x00000001 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_ENABLE__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_MANUAL_MODE__MSK                                              (  0x00000002 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_MANUAL_MODE__SHFT                                             (  0x00000001 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_BAND_START__MSK                                                   (  0x000000FC )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_BAND_START__SHFT                                                  (  0x00000002 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FINE_START__MSK                                                   (  0x00003F00 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FINE_START__SHFT                                                  (  0x00000008 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_DELAY_COUNT__MSK                                                  (  0x0003C000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_DELAY_COUNT__SHFT                                                 (  0x0000000E )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_USE_DEMETED_CHECK__MSK                                            (  0x00040000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_USE_DEMETED_CHECK__SHFT                                           (  0x00000012 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_LOCKED_COUNT_THRESHOLD__MSK                                       (  0x00780000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_LOCKED_COUNT_THRESHOLD__SHFT                                      (  0x00000013 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_BYPASS_BAND__MSK                                              (  0x00800000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_BYPASS_BAND__SHFT                                             (  0x00000017 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_BYPASS_FINE__MSK                                              (  0x01000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_BYPASS_FINE__SHFT                                             (  0x00000018 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_PERSISTENT_MODE__MSK                                          (  0x02000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_FLL_PERSISTENT_MODE__SHFT                                         (  0x00000019 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_TOO_FAST_STATUS__MSK                                              (  0x04000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_TOO_FAST_STATUS__SHFT                                             (  0x0000001A )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_TOO_SLOW_STATUS__MSK                                              (  0x08000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_TOO_SLOW_STATUS__SHFT                                             (  0x0000001B )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_LOCKED__MSK                                                       (  0x10000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1_VCO2_LOCKED__SHFT                                                      (  0x0000001C )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1__ADR                                                                   (  0x0000006c )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1__WIDTH                                                                 (  29 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1__POR                                                                   (  0x00249F00 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL1__MSK                                                                   (  0x1FFFFFFF )


// Word Address 0x00000070 : DDR_MVP_PLL_VCO2_FLL_CONTROL2 (RW)
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2_VCO2_FLL_REFCLK_COUNT__MSK                                             (  0x000000FF )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2_VCO2_FLL_REFCLK_COUNT__SHFT                                            (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2_VCO2_FLL_VCO_COUNT_TARGET__MSK                                         (  0x00FFFF00 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2_VCO2_FLL_VCO_COUNT_TARGET__SHFT                                        (  0x00000008 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2_VCO2_FLL_RANGE__MSK                                                    (  0x1F000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2_VCO2_FLL_RANGE__SHFT                                                   (  0x00000018 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2__ADR                                                                   (  0x00000070 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2__WIDTH                                                                 (  29 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2__POR                                                                   (  0x0400D008 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL2__MSK                                                                   (  0x1FFFFFFF )


// Word Address 0x00000074 : DDR_MVP_PLL_VCO2_FLL_CONTROL3 (RW)
#define DDR_MVP_PLL_VCO2_FLL_CONTROL3_VCO2_FLL_BAND_THRESH__MSK                                              (  0x0000003F )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL3_VCO2_FLL_BAND_THRESH__SHFT                                             (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL3__ADR                                                                   (  0x00000074 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL3__WIDTH                                                                 (   6 )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL3__POR                                                                   (  0x0000003C )
#define DDR_MVP_PLL_VCO2_FLL_CONTROL3__MSK                                                                   (  0x0000003F )


// Word Address 0x00000078 : DDR_MVP_PLL_VCO2_FLL_BAND_STATUS (R)
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_BAND_STATUS__MSK                                               (  0x0000003F )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_BAND_STATUS__SHFT                                              (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_BAND_PREV_STATUS__MSK                                          (  0x00000FC0 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_BAND_PREV_STATUS__SHFT                                         (  0x00000006 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_FINE_STATUS__MSK                                               (  0x0003F000 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_FINE_STATUS__SHFT                                              (  0x0000000C )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_FINE_PREV_STATUS__MSK                                          (  0x00FC0000 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS_VCO2_FINE_PREV_STATUS__SHFT                                         (  0x00000012 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS__ADR                                                                (  0x00000078 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS__WIDTH                                                              (  24 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS__POR                                                                (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_BAND_STATUS__MSK                                                                (  0x00FFFFFF )


// Word Address 0x0000007c : DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS (R)
#define DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS_VCO2_VCO_COUNT__MSK                                                (  0x0000FFFF )
#define DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS_VCO2_VCO_COUNT__SHFT                                               (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS__ADR                                                               (  0x0000007c )
#define DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS__WIDTH                                                             (  16 )
#define DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS__POR                                                               (  0x00000000 )
#define DDR_MVP_PLL_VCO2_FLL_COUNT_STATUS__MSK                                                               (  0x0000FFFF )


// Word Address 0x00000080 : DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS (RW)
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_INT__MSK                                                     (  0x000001FF )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_INT__SHFT                                                    (  0x00000000 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_FRAC__MSK                                                    (  0x01FFFE00 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_FRAC__SHFT                                                   (  0x00000009 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_FRAC_EN__MSK                                                 (  0x02000000 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_FRAC_EN__SHFT                                                (  0x00000019 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_FRAC_EN_AUTO__MSK                                            (  0x04000000 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS_VCO2_FRAC_EN_AUTO__SHFT                                           (  0x0000001A )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS__ADR                                                              (  0x00000080 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS__WIDTH                                                            (  27 )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS__POR                                                              (  0x0400000A )
#define DDR_MVP_PLL_VCO2_INT_FRAC_SETTINGS__MSK                                                              (  0x07FFFFFF )


// Word Address 0x00000084 : DDR_MVP_PLL_VCO2_PROP_GAINS (RW)
#define DDR_MVP_PLL_VCO2_PROP_GAINS_VCO2_PROP_GAIN__MSK                                                      (  0x0000001F )
#define DDR_MVP_PLL_VCO2_PROP_GAINS_VCO2_PROP_GAIN__SHFT                                                     (  0x00000000 )
#define DDR_MVP_PLL_VCO2_PROP_GAINS__ADR                                                                     (  0x00000084 )
#define DDR_MVP_PLL_VCO2_PROP_GAINS__WIDTH                                                                   (   5 )
#define DDR_MVP_PLL_VCO2_PROP_GAINS__POR                                                                     (  0x0000000A )
#define DDR_MVP_PLL_VCO2_PROP_GAINS__MSK                                                                     (  0x0000001F )


// Word Address 0x00000088 : DDR_MVP_PLL_VCO2_SSC_CONTROLS (RW)
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_ENABLE__MSK                                                   (  0x00000001 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_ENABLE__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_STEPSIZE__MSK                                                 (  0x000007FE )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_STEPSIZE__SHFT                                                (  0x00000001 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_AMP__MSK                                                      (  0x0FFFF800 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_AMP__SHFT                                                     (  0x0000000B )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_COUNT_CYCLES__MSK                                             (  0x10000000 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_COUNT_CYCLES__SHFT                                            (  0x0000001C )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_CENTER_SPREAD__MSK                                            (  0x20000000 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS_VCO2_SSC_CENTER_SPREAD__SHFT                                           (  0x0000001D )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS__ADR                                                                   (  0x00000088 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS__WIDTH                                                                 (  30 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS__POR                                                                   (  0x00000000 )
#define DDR_MVP_PLL_VCO2_SSC_CONTROLS__MSK                                                                   (  0x3FFFFFFF )


// Word Address 0x0000008c : DDR_MVP_PLL_STATE_MACHINE_CONTROLS (RW)
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_BIAS_SETTLE_COUNT__MSK                                            (  0x000000FF )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_BIAS_SETTLE_COUNT__SHFT                                           (  0x00000000 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_PRE_LOCKING_COUNT__MSK                                            (  0x0000FF00 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_PRE_LOCKING_COUNT__SHFT                                           (  0x00000008 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_SWITCH_COUNT__MSK                                                 (  0x000F0000 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_SWITCH_COUNT__SHFT                                                (  0x00000010 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_DISABLE_LOCK_DET_AFTER_LOCK__MSK                                  (  0x00100000 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_DISABLE_LOCK_DET_AFTER_LOCK__SHFT                                 (  0x00000014 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_FLL_INITIAL_SETTLE__MSK                                           (  0x01E00000 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS_FLL_INITIAL_SETTLE__SHFT                                          (  0x00000015 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS__ADR                                                              (  0x0000008c )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS__WIDTH                                                            (  25 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS__POR                                                              (  0x00810408 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS__MSK                                                              (  0x01FFFFFF )


// Word Address 0x00000090 : DDR_MVP_PLL_STATE_MACHINE_CONTROLS2 (RW)
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_PRE_SWITCH_TIME__MSK                                             (  0x0000000F )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_PRE_SWITCH_TIME__SHFT                                            (  0x00000000 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_SWITCH_RESET_TIME__MSK                                           (  0x000000F0 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_SWITCH_RESET_TIME__SHFT                                          (  0x00000004 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_SWITCH_1_TIME__MSK                                               (  0x0000FF00 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_SWITCH_1_TIME__SHFT                                              (  0x00000008 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_SWITCH_2_TIME__MSK                                               (  0x00FF0000 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2_SWITCH_2_TIME__SHFT                                              (  0x00000010 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2__ADR                                                             (  0x00000090 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2__WIDTH                                                           (  24 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2__POR                                                             (  0x00010311 )
#define DDR_MVP_PLL_STATE_MACHINE_CONTROLS2__MSK                                                             (  0x00FFFFFF )


// Word Address 0x00000094 : DDR_MVP_PLL_INTR_GAINS (RW)
#define DDR_MVP_PLL_INTR_GAINS_NORMAL_INT_GAIN__MSK                                                          (  0x0000001F )
#define DDR_MVP_PLL_INTR_GAINS_NORMAL_INT_GAIN__SHFT                                                         (  0x00000000 )
#define DDR_MVP_PLL_INTR_GAINS__ADR                                                                          (  0x00000094 )
#define DDR_MVP_PLL_INTR_GAINS__WIDTH                                                                        (   5 )
#define DDR_MVP_PLL_INTR_GAINS__POR                                                                          (  0x0000000F )
#define DDR_MVP_PLL_INTR_GAINS__MSK                                                                          (  0x0000001F )


// Word Address 0x00000098 : DDR_MVP_PLL_INTR_PROP_FL_GAINS (RW)
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS_FL_INT_GAIN__MSK                                                      (  0x0000001F )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS_FL_INT_GAIN__SHFT                                                     (  0x00000000 )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS_FL_PROP_GAIN__MSK                                                     (  0x000003E0 )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS_FL_PROP_GAIN__SHFT                                                    (  0x00000005 )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS__ADR                                                                  (  0x00000098 )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS__WIDTH                                                                (  10 )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS__POR                                                                  (  0x000003DE )
#define DDR_MVP_PLL_INTR_PROP_FL_GAINS__MSK                                                                  (  0x000003FF )


// Word Address 0x0000009c : DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE (RW)
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_INT_GAIN__MSK                                                   (  0x0000001F )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_INT_GAIN__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_INT_GAIN_MUX__MSK                                               (  0x00000020 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_INT_GAIN_MUX__SHFT                                              (  0x00000005 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_PROP_GAIN__MSK                                                  (  0x000007C0 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_PROP_GAIN__SHFT                                                 (  0x00000006 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_PROP_GAIN_MUX__MSK                                              (  0x00000800 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE_PROP_GAIN_MUX__SHFT                                             (  0x0000000B )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE__ADR                                                            (  0x0000009c )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE__WIDTH                                                          (  12 )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE__POR                                                            (  0x0000024F )
#define DDR_MVP_PLL_INTR_PROP_GAINS_OVERRIDE__MSK                                                            (  0x00000FFF )


// Word Address 0x000000a0 : DDR_MVP_PLL_LOCK_DET_SETTINGS (RW)
#define DDR_MVP_PLL_LOCK_DET_SETTINGS_LD_REFCLK_CYCLES__MSK                                                  (  0x0000FFFF )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS_LD_REFCLK_CYCLES__SHFT                                                 (  0x00000000 )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS_LD_RANGE__MSK                                                          (  0x003F0000 )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS_LD_RANGE__SHFT                                                         (  0x00000010 )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS__ADR                                                                   (  0x000000a0 )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS__WIDTH                                                                 (  22 )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS__POR                                                                   (  0x00040200 )
#define DDR_MVP_PLL_LOCK_DET_SETTINGS__MSK                                                                   (  0x003FFFFF )


// Word Address 0x000000a4 : DDR_MVP_PLL_FASTLOCK_DET_SETTINGS (RW)
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS_FASTLD_REFCLK_CYCLES__MSK                                          (  0x0000FFFF )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS_FASTLD_REFCLK_CYCLES__SHFT                                         (  0x00000000 )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS_FASTLD_RANGE__MSK                                                  (  0x003F0000 )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS_FASTLD_RANGE__SHFT                                                 (  0x00000010 )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS__ADR                                                               (  0x000000a4 )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS__WIDTH                                                             (  22 )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS__POR                                                               (  0x00080100 )
#define DDR_MVP_PLL_FASTLOCK_DET_SETTINGS__MSK                                                               (  0x003FFFFF )


// Word Address 0x000000a8 : DDR_MVP_PLL_ANALOG_EN_RESET (RW)
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_EN__MSK                                                              (  0x00000001 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_EN__SHFT                                                             (  0x00000000 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_EN_MUX__MSK                                                          (  0x00000002 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_EN_MUX__SHFT                                                         (  0x00000001 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_RESET__MSK                                                           (  0x00000004 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_RESET__SHFT                                                          (  0x00000002 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_RESET_MUX__MSK                                                       (  0x00000008 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_PLL_RESET_MUX__SHFT                                                      (  0x00000003 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_FBDIV_SEL__MSK                                                           (  0x00001FF0 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_FBDIV_SEL__SHFT                                                          (  0x00000004 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_FBDIV_SEL_MUX__MSK                                                       (  0x00002000 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_FBDIV_SEL_MUX__SHFT                                                      (  0x0000000D )
#define DDR_MVP_PLL_ANALOG_EN_RESET_VCO_SEL__MSK                                                             (  0x0000C000 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_VCO_SEL__SHFT                                                            (  0x0000000E )
#define DDR_MVP_PLL_ANALOG_EN_RESET_VCO_SEL_MUX__MSK                                                         (  0x00010000 )
#define DDR_MVP_PLL_ANALOG_EN_RESET_VCO_SEL_MUX__SHFT                                                        (  0x00000010 )
#define DDR_MVP_PLL_ANALOG_EN_RESET__ADR                                                                     (  0x000000a8 )
#define DDR_MVP_PLL_ANALOG_EN_RESET__WIDTH                                                                   (  17 )
#define DDR_MVP_PLL_ANALOG_EN_RESET__POR                                                                     (  0x00000000 )
#define DDR_MVP_PLL_ANALOG_EN_RESET__MSK                                                                     (  0x0001FFFF )


// Word Address 0x000000ac : DDR_MVP_PLL_MODE_DTST_MISC (RW)
#define DDR_MVP_PLL_MODE_DTST_MISC_BIAS_LVL__MSK                                                             (  0x0000000F )
#define DDR_MVP_PLL_MODE_DTST_MISC_BIAS_LVL__SHFT                                                            (  0x00000000 )
#define DDR_MVP_PLL_MODE_DTST_MISC_CP_INT_MODE__MSK                                                          (  0x00000010 )
#define DDR_MVP_PLL_MODE_DTST_MISC_CP_INT_MODE__SHFT                                                         (  0x00000004 )
#define DDR_MVP_PLL_MODE_DTST_MISC_EN_LOCK_DET__MSK                                                          (  0x00000020 )
#define DDR_MVP_PLL_MODE_DTST_MISC_EN_LOCK_DET__SHFT                                                         (  0x00000005 )
#define DDR_MVP_PLL_MODE_DTST_MISC_EN_LOCK_DET_MUX__MSK                                                      (  0x00000040 )
#define DDR_MVP_PLL_MODE_DTST_MISC_EN_LOCK_DET_MUX__SHFT                                                     (  0x00000006 )
#define DDR_MVP_PLL_MODE_DTST_MISC_DIV16EN__MSK                                                              (  0x00000080 )
#define DDR_MVP_PLL_MODE_DTST_MISC_DIV16EN__SHFT                                                             (  0x00000007 )
#define DDR_MVP_PLL_MODE_DTST_MISC_BIAS_SEL__MSK                                                             (  0x00000100 )
#define DDR_MVP_PLL_MODE_DTST_MISC_BIAS_SEL__SHFT                                                            (  0x00000008 )
#define DDR_MVP_PLL_MODE_DTST_MISC__ADR                                                                      (  0x000000ac )
#define DDR_MVP_PLL_MODE_DTST_MISC__WIDTH                                                                    (   9 )
#define DDR_MVP_PLL_MODE_DTST_MISC__POR                                                                      (  0x00000008 )
#define DDR_MVP_PLL_MODE_DTST_MISC__MSK                                                                      (  0x000001FF )


// Word Address 0x000000b0 : DDR_MVP_PLL_PROP_CTRLS (RW)
#define DDR_MVP_PLL_PROP_CTRLS_PROP_C_CTRL__MSK                                                              (  0x00000003 )
#define DDR_MVP_PLL_PROP_CTRLS_PROP_C_CTRL__SHFT                                                             (  0x00000000 )
#define DDR_MVP_PLL_PROP_CTRLS_PROP_R_CTRL__MSK                                                              (  0x0000000C )
#define DDR_MVP_PLL_PROP_CTRLS_PROP_R_CTRL__SHFT                                                             (  0x00000002 )
#define DDR_MVP_PLL_PROP_CTRLS__ADR                                                                          (  0x000000b0 )
#define DDR_MVP_PLL_PROP_CTRLS__WIDTH                                                                        (   4 )
#define DDR_MVP_PLL_PROP_CTRLS__POR                                                                          (  0x00000000 )
#define DDR_MVP_PLL_PROP_CTRLS__MSK                                                                          (  0x0000000F )


// Word Address 0x000000b4 : DDR_MVP_PLL_REFCLK_CONTROLS (RW)
#define DDR_MVP_PLL_REFCLK_CONTROLS_PFD_MODE__MSK                                                            (  0x00000003 )
#define DDR_MVP_PLL_REFCLK_CONTROLS_PFD_MODE__SHFT                                                           (  0x00000000 )
#define DDR_MVP_PLL_REFCLK_CONTROLS_SEL_REFCLK_ALT__MSK                                                      (  0x00000004 )
#define DDR_MVP_PLL_REFCLK_CONTROLS_SEL_REFCLK_ALT__SHFT                                                     (  0x00000002 )
#define DDR_MVP_PLL_REFCLK_CONTROLS__ADR                                                                     (  0x000000b4 )
#define DDR_MVP_PLL_REFCLK_CONTROLS__WIDTH                                                                   (   3 )
#define DDR_MVP_PLL_REFCLK_CONTROLS__POR                                                                     (  0x00000000 )
#define DDR_MVP_PLL_REFCLK_CONTROLS__MSK                                                                     (  0x00000007 )


// Word Address 0x000000b8 : DDR_MVP_PLL_CLKGATE_DISABLES (RW)
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_FBCLK_GATE__MSK                                                   (  0x00000001 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_FBCLK_GATE__SHFT                                                  (  0x00000000 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_VCO0_CLK_GATE__MSK                                                (  0x00000002 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_VCO0_CLK_GATE__SHFT                                               (  0x00000001 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_VCO1_CLK_GATE__MSK                                                (  0x00000004 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_VCO1_CLK_GATE__SHFT                                               (  0x00000002 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_VCO2_CLK_GATE__MSK                                                (  0x00000008 )
#define DDR_MVP_PLL_CLKGATE_DISABLES_FORCE_VCO2_CLK_GATE__SHFT                                               (  0x00000003 )
#define DDR_MVP_PLL_CLKGATE_DISABLES__ADR                                                                    (  0x000000b8 )
#define DDR_MVP_PLL_CLKGATE_DISABLES__WIDTH                                                                  (   4 )
#define DDR_MVP_PLL_CLKGATE_DISABLES__POR                                                                    (  0x00000000 )
#define DDR_MVP_PLL_CLKGATE_DISABLES__MSK                                                                    (  0x0000000F )


#endif /* _DDR_MVP_PLL_CSR_H_ */
