/**
 * Copyright (c) 2021 Wavious LLC.
 *
 * SPDX-License-Identifier: GPL-3.0
 */
/****************************************************************************
*****************************************************************************
** Tool used: cfg_table_creator.py
** Generated by: wpatty
** Date: 04/08/21 14:53:26
** Code version: 1.0
** Input file used: DDR_TABLES.xlsx
*****************************************************************************
****************************************************************************/

#ifndef _WDDR_TABLE_DEFS_H_
#define _WDDR_TABLE_DEFS_H_

#include "table_vals.h"

#define WDDR_PHY_FREQ_NUM       (4)
#define WDDR_PHY_VALID_FREQ_NUM (4)
#define FREQ_VALID              (1)
#define FREQ_INVALID            (0)

#define WDDR_FREQ_VALID_TABLE {                                                                                        \
    FREQ_VALID,                                                                                                        \
    FREQ_VALID,                                                                                                        \
    FREQ_VALID,                                                                                                        \
    FREQ_VALID,                                                                                                        \
}

#define WDDR_TABLE_CAL(name) {                                                                                         \
    .common = WDDR_TABLE_CAL__WDDR__COMMON(name),                                                                      \
    .freq[0] = WDDR_TABLE_CAL__WDDR__FREQID_0(name),                                                                   \
    .freq[1] = WDDR_TABLE_CAL__WDDR__FREQID_1(name),                                                                   \
    .freq[2] = WDDR_TABLE_CAL__WDDR__FREQID_2(name),                                                                   \
    .freq[3] = WDDR_TABLE_CAL__WDDR__FREQID_3(name),                                                                   \
}

#define WDDR_TABLE_CFG(name) {                                                                                         \
    .common = WDDR_TABLE_CFG__WDDR__COMMON(name),                                                                      \
    .freq[0] = WDDR_TABLE_CFG__WDDR__FREQID_0(name),                                                                   \
    .freq[1] = WDDR_TABLE_CFG__WDDR__FREQID_1(name),                                                                   \
    .freq[2] = WDDR_TABLE_CFG__WDDR__FREQID_2(name),                                                                   \
    .freq[3] = WDDR_TABLE_CFG__WDDR__FREQID_3(name),                                                                   \
}

#define WDDR_TABLE(name) {                                                                                             \
    .cal = WDDR_TABLE_CAL(name),                                                                                       \
    .cfg = WDDR_TABLE_CFG(name),                                                                                       \
    .valid = WDDR_FREQ_VALID_TABLE,                                                                                    \
}

#define DECLARE_WDDR_TABLE(name)                                                                                       \
    wddr_table_t name = WDDR_TABLE(name)

#endif /* _WDDR_TABLE_DEFS_H_ */
